import { t2 } from './i18n';

const small = t2('What is the smallest version you could finish today?', 'Qual è la versione più piccola che potresti finire oggi?');
const avoid = t2('Which part are you avoiding, and why?', 'Quale parte stai evitando, e perché?');
const m = (n: string, it: string, title: [string, string], blurb: [string, string]) => [t2(n, it), t2(title[0], title[1]), t2(blurb[0], blurb[1])];
// Concrete briefs for each mission live in missions.ts (MX), same field and index.
// Null prototype (set below) so FIELDS[key] is a safe check for keys from URLs or storage, even "__proto__".
export const FIELDS: Record<string, { m: string[][]; idea: string; qs: string[] }> = {
  Design: { m: [
    m('Mission 002 · startup partner', 'Missione 002 · partner startup', ['Save a sign-up flow', 'Salva un flusso di registrazione'], ['Only 9% of Lumo users finish sign-up. Cut 5 screens down to 3.', 'Solo il 9% degli utenti di Lumo finisce la registrazione. Riduci 5 schermate a 3.']),
    m('Mission 003 · KERN', 'Missione 003 · KERN', ['Rescue a booking form', 'Salva un modulo di prenotazione'], ['14 fields, half the bookings lost. Make it feel like a chat.', '14 campi, metà delle prenotazioni perse. Fallo sembrare una chiacchierata.']),
    m('Mission 004 · studio client', 'Missione 004 · cliente studio', ['Design an empty screen', 'Progetta una schermata vuota'], ['7 in 10 new users leave at a blank screen. Give them a reason to stay.', '7 nuovi utenti su 10 se ne vanno davanti a una schermata vuota. Dai loro un motivo per restare.']),
    m('Mission 005 · outdoor app partner', 'Missione 005 · partner app outdoor', ['Fix an error message', 'Correggi un messaggio di errore'], ['8 in 10 hikers who see a raw error code close Cairn. Make it calm and useful.', '8 escursionisti su 10 che vedono un codice di errore chiudono Cairn. Rendi il messaggio calmo e utile.']),
    m('Mission 006 · KERN', 'Missione 006 · KERN', ['Design a share card', 'Progetta una card da condividere'], ['Nobody posts Topout’s grey stats table. Turn 6 facts into one card worth posting.', 'Nessuno pubblica la tabella grigia di Topout. Trasforma 6 dati in una card che valga la pena pubblicare.']),
    m('Mission 007 · studio client', 'Missione 007 · cliente studio', ['Build a checkout with a partner', 'Costruisci un checkout con un partner'], ['6 in 10 shoppers quit at shipping. One arranges the screen, one writes the words.', '6 acquirenti su 10 mollano alla spedizione. Uno dispone la schermata, uno scrive le parole.']),
  ], idea: t2('Your idea: a 3-step onboarding with one clear choice at the start.', 'La tua idea: un onboarding in 3 passi con una scelta chiara all’inizio.'), qs: [t2('What would make the first step easier for someone brand new?', 'Cosa renderebbe il primo passo più facile per chi è completamente nuovo?'), avoid, small] },
  Writing: { m: [
    m('Mission 002 · newsletter partner', 'Missione 002 · partner newsletter', ['Make a hard idea easy', 'Rendi facile un’idea difficile'], ['A newsletter’s readers can’t follow one paragraph. Rewrite it for a 15-year-old.', 'I lettori di una newsletter non seguono un paragrafo. Riscrivilo per un quindicenne.']),
    m('Mission 003 · KERN', 'Missione 003 · KERN', ['Rewrite an email nobody acts on', 'Riscrivi un’email a cui nessuno risponde'], ['Monday’s email, Wednesday’s silence. Make people act today.', 'Email di lunedì, silenzio di mercoledì. Fai agire le persone oggi.']),
    m('Mission 004 · studio client', 'Missione 004 · cliente studio', ['Write with a partner', 'Scrivi con un partner'], ['A zine gives you one first line. Build the story in five sentences, taking turns.', 'Una zine ti dà una prima riga. Costruisci il racconto in cinque frasi, a turno.']),
    m('Mission 005 · small shop partner', 'Missione 005 · partner piccolo negozio', ['Rescue a dull product page', 'Salva una scheda prodotto spenta'], ['A candle gets 400 visits a week and 2 sales. Rewrite its page so a stranger wants one.', 'Una candela ha 400 visite a settimana e 2 vendite. Riscrivi la sua pagina così che uno sconosciuto ne voglia una.']),
    m('Mission 006 · KERN', 'Missione 006 · KERN', ['Write an intro to say out loud', 'Scrivi una presentazione da dire a voce'], ['Nine facts about a speaker, 15 seconds to use. Pick three and make the room lean in.', 'Nove fatti su chi parla, 15 secondi a disposizione. Scegline tre e fai tendere l’orecchio alla sala.']),
    m('Mission 007 · studio client', 'Missione 007 · cliente studio', ['Turn a complaint into a deal', 'Trasforma un reclamo in un accordo'], ['A gift fern arrives broken. One writes the customer, one writes support, taking turns.', 'Una felce regalo arriva rotta. Uno scrive come cliente, uno come assistenza, a turno.']),
  ], idea: t2('Your idea: a first line that makes a stranger keep reading.', 'La tua idea: una prima riga che fa continuare a leggere uno sconosciuto.'), qs: [t2('Who is this for, exactly?', 'Per chi è, esattamente?'), t2('Which sentence would you cut first?', 'Quale frase taglieresti per prima?'), small] },
  Code: { m: [
    m('Mission 002 · startup partner', 'Missione 002 · partner startup', ['Fix a dead button', 'Correggi un pulsante morto'], ['Linkly’s “Copy link” does nothing. Find why, fix it, explain it.', 'Il “Copia link” di Linkly non fa nulla. Scopri perché, correggilo, spiegalo.']),
    m('Mission 003 · KERN', 'Missione 003 · KERN', ['Build a bill splitter', 'Costruisci un dividi-conto'], ['Write the function that splits a bill with tip. Three tests must pass.', 'Scrivi la funzione che divide un conto con la mancia. Tre test devono passare.']),
    m('Mission 004 · studio client', 'Missione 004 · cliente studio', ['Build with a partner', 'Costruisci con un partner'], ['A dark mode toggle that remembers the choice. One does the look, one the logic.', 'Un interruttore per la modalità scura che ricorda la scelta. Uno fa l’aspetto, uno la logica.']),
    m('Mission 005 · book app partner', 'Missione 005 · partner app di libri', ['Fix a page counter', 'Correggi un contatore di pagine'], ['Shelfie shows 2 pages for 23 books. Find both mistakes.', 'Shelfie mostra 2 pagine per 23 libri. Trova entrambi gli errori.']),
    m('Mission 006 · KERN', 'Missione 006 · KERN', ['Build a streak counter', 'Costruisci un contatore di serie'], ['Count the days in a row, back from today. Write it and prove it with three examples.', 'Conta i giorni di fila, a ritroso da oggi. Scrivilo e dimostralo con tre esempi.']),
    m('Mission 007 · studio client', 'Missione 007 · cliente studio', ['Test and build with a partner', 'Testa e costruisci con un partner'], ['A word counter for a blog editor. One writes the tests, one the function.', 'Un contatore di parole per un editor di blog. Uno scrive i test, uno la funzione.']),
  ], idea: t2('Your idea: a tool that removes one repeated step from your day.', 'La tua idea: uno strumento che elimina un passaggio ripetuto della tua giornata.'), qs: [t2('What is the one thing it must do?', 'Qual è l’unica cosa che deve fare?'), avoid, small] },
  Video: { m: [
    m('Mission 002 · brand partner', 'Missione 002 · brand partner', ['Cut one clear story', 'Monta una storia chiara'], ['12 raw clips from a bakery. Pick the shots for a 20-second reel.', '12 clip grezze di un forno. Scegli le inquadrature per un reel di 20 secondi.']),
    m('Mission 003 · KERN', 'Missione 003 · KERN', ['Plan a 30-second explainer', 'Pianifica una spiegazione di 30 secondi'], ['Teach one thing you know. Hook, claim, show, close.', 'Insegna una cosa che sai. Aggancio, tesi, esempio, chiusa.']),
    m('Mission 004 · studio client', 'Missione 004 · cliente studio', ['Make it with a partner', 'Fallo con un partner'], ['A 15-second clip for a steel bottle. One picks the shots, one the order and sound.', 'Un video di 15 secondi per una borraccia. Uno sceglie le inquadrature, uno ordine e suono.']),
    m('Mission 005 · bike shop partner', 'Missione 005 · partner officina', ['Speed up a slow video', 'Dai ritmo a un video lento'], ['A bike shop’s repair video runs 41 seconds. Cut it to 25 seconds and make it open on the action.', 'Il video di riparazione di un negozio di bici dura 41 secondi. Portalo a 25 secondi e fallo aprire sull’azione.']),
    m('Mission 006 · KERN', 'Missione 006 · KERN', ['Storyboard a channel intro', 'Fai lo storyboard di un’intro'], ['A new herb channel needs an intro that makes a stranger stay. Plan 15 to 20 seconds, frame by frame.', 'Un nuovo canale sulle erbe aromatiche ha bisogno di un’intro che faccia restare uno sconosciuto. Pianifica 15-20 secondi, inquadratura per inquadratura.']),
    m('Mission 007 · studio client', 'Missione 007 · cliente studio', ['Make a teaser with a partner', 'Fai un teaser con un partner'], ['A game room has a party on Friday. One writes the words, one plans the shots.', 'Una sala giochi organizza una festa venerdì. Uno scrive le parole, uno pianifica le inquadrature.']),
  ], idea: t2('Your idea: open on the surprise, not on the logo.', 'La tua idea: apri con la sorpresa, non con il logo.'), qs: [t2('What should someone feel in the first second?', 'Cosa dovrebbe sentire qualcuno nel primo secondo?'), avoid, small] },
  Selling: { m: [
    m('Mission 002 · small business partner', 'Missione 002 · piccola impresa partner', ['Get a stranger to say yes', 'Fatti dire di sì da uno sconosciuto'], ['Pitch a €12 pastry box to Marta, who already has a café next door.', 'Proponi una box di pasticcini da 12 € a Marta, che ha già un bar accanto.']),
    m('Mission 003 · KERN', 'Missione 003 · KERN', ['Write a message that gets a reply', 'Scrivi un messaggio che riceve risposta'], ['Dana ignored three messages. Write the fourth, in 50 words.', 'Dana ha ignorato tre messaggi. Scrivi il quarto, in 50 parole.']),
    m('Mission 004 · studio client', 'Missione 004 · cliente studio', ['Sell with a partner', 'Vendi con un partner'], ['One sells headphones, one pushes back. Handle three objections.', 'Uno vende cuffie, uno si oppone. Gestisci tre obiezioni.']),
    m('Mission 005 · small business partner', 'Missione 005 · piccola impresa partner', ['Calm down a pushy pitch', 'Smorza una proposta insistente'], ['A gym’s pushy text got no reply. Rewrite it so it helps, not pressures.', 'Il messaggio insistente di una palestra non ha avuto risposta. Riscrivilo perché aiuti, non pressi.']),
    m('Mission 006 · KERN', 'Missione 006 · KERN', ['Fill a repair stall’s first Wednesday', 'Riempi il primo mercoledì di un banco riparazioni'], ['A new bike stall has 8 facts and no customers. Write a flyer of up to 40 words.', 'Un nuovo banco per bici ha 8 fatti e nessun cliente. Scrivi un volantino di massimo 40 parole.']),
    m('Mission 007 · studio client', 'Missione 007 · cliente studio', ['Haggle to a fair price', 'Tratta fino a un prezzo giusto'], ['A café wants 200 menus, a print shop wants a fair price. Trade, don’t just cut the price.', 'Un bar vuole 200 menu, una tipografia un prezzo giusto. Scambia, non limitarti ad abbassare il prezzo.']),
  ], idea: t2('Your idea: lead with the problem, not the product.', 'La tua idea: parti dal problema, non dal prodotto.'), qs: [t2('Who needs this most, by name?', 'Chi ne ha più bisogno, con nome e cognome?'), t2('What would make them say no?', 'Cosa li farebbe dire di no?'), small] },
  Music: { m: [
    m('Mission 002 · brand partner', 'Missione 002 · brand partner', ['Give a small brand a sound', 'Dai un suono a un piccolo brand'], ['A coffee roaster wants a 6-second sound: warm, slow, Sunday.', 'Una torrefazione vuole un suono di 6 secondi: caldo, lento, domenicale.']),
    m('Mission 003 · KERN', 'Missione 003 · KERN', ['Remix something you love', 'Remixa qualcosa che ami'], ['Plan a remix on one card: keep, change, add, drop.', 'Pianifica un remix su una carta: tieni, cambia, aggiungi, togli.']),
    m('Mission 004 · studio client', 'Missione 004 · cliente studio', ['Make it with a partner', 'Fallo con un partner'], ['A 15-second sneaker ad over C G Am F. One writes the melody, one the words.', 'Una pubblicità di 15 secondi di sneaker su DO SOL LAm FA. Uno scrive la melodia, uno le parole.']),
    m('Mission 005 · band partner', 'Missione 005 · partner band', ['Fix a chorus that says one thing', 'Aggiusta un ritornello che dice una cosa sola'], ['Four lines, one idea, said four times. Give each line something new.', 'Quattro righe, una sola idea ripetuta. Dai a ogni riga qualcosa di nuovo.']),
    m('Mission 006 · KERN', 'Missione 006 · KERN', ['Plan a night of music', 'Pianifica una serata di musica'], ['A rooftop bar, 6 to 11 pm. Shape how the energy rises and falls.', 'Un rooftop bar, dalle 18 alle 23. Disegna come l’energia sale e scende.']),
    m('Mission 007 · event client', 'Missione 007 · cliente evento', ['Make a beat people answer', 'Fai un ritmo a cui si risponde'], ['A charity run needs a start-line chant. One writes the rhythm, one the call and answer.', 'Una corsa benefica vuole un coro alla partenza. Uno scrive il ritmo, uno richiamo e risposta.']),
  ], idea: t2('Your idea: one repeating sound people remember.', 'La tua idea: un suono che si ripete e che le persone ricordano.'), qs: [t2('What should it feel like in the first two seconds?', 'Che effetto dovrebbe fare nei primi due secondi?'), avoid, small] },
};
Object.setPrototypeOf(FIELDS, null);
