import { t2 } from './i18n';

const small = t2('What is the smallest version you could finish today?', 'Qual è la versione più piccola che potresti finire oggi?');
const avoid = t2('Which part are you avoiding, and why?', 'Quale parte stai evitando, e perché?');
const m = (n: string, it: string, title: [string, string], blurb: [string, string]) => [t2(n, it), t2(title[0], title[1]), t2(blurb[0], blurb[1])];
// Concrete briefs for each mission live in missions.ts (MX), same field and index.
// Null prototype (set below) so FIELDS[key] is a safe check for keys from URLs or storage, even "__proto__".
export const FIELDS: Record<string, { m: string[][]; idea: string; qs: string[] }> = {
  Design: { m: [
    m('Mission 001 · crowded story', 'Missione 001 · storia strapiena', ['Make a busy story readable', 'Rendi leggibile una storia troppo piena'], ['7 things on one story. People swipe past in a second.', '7 cose in una sola storia. La gente scorre via in un secondo.']),
    m('Mission 002 · bar sticker', 'Missione 002 · adesivo del bar', ['Describe a sticker for a bar', 'Descrivi un adesivo per un bar'], ['Bar Ficus has no logo. Rosa wants a sticker for the door.', 'Bar Ficus non ha un logo. Rosa vuole un adesivo per la porta.']),
    m('Mission 003 · dream room', 'Missione 003 · stanza dei sogni', ['Describe 6 pictures for Elena’s room', 'Descrivi 6 immagini per la stanza di Elena'], ['One sentence, one bare room. Show Elena the feeling in 6 pictures.', 'Una frase, una stanza vuota. Mostra a Elena la sensazione in 6 immagini.']),
    m('Mission 004 · sneaker photo', 'Missione 004 · foto delle sneaker', ['Fix a dark sneaker photo', 'Sistema una foto buia di sneaker'], ['No messages in 5 days. The shoes are fine. The photo is the problem.', 'Nessun messaggio in 5 giorni. Le scarpe vanno bene. Il problema è la foto.']),
    m('Mission 005 · swipe cover', 'Missione 005 · copertina del carosello', ['Plan a post’s first picture', 'Pianifica la prima immagine di un post'], ['5 good tips and no first picture yet. Make people want the next one.', '5 buoni consigli e ancora nessuna prima immagine. Fai venire voglia di vedere la prossima.']),
    m('Mission 006 · two thumbnails', 'Missione 006 · due miniature', ['Plan 2 thumbnails, pick the winner', 'Pianifica 2 miniature, scegli la vincente'], ['One video, two thumbnails. Whichever gets tapped more wins.', 'Un video, due miniature. Vince quella su cui si tocca di più.']),
  ], idea: t2('Your idea: a poster for Friday’s flat dinner, with one big word, red letters on cream paper and a tiny drawn fork.', 'La tua idea: un poster per la cena di venerdì in casa, con una sola parola grande, lettere rosse su carta crema e una piccola forchetta disegnata.'), qs: [t2('What does the eye land on first?', 'Su cosa cade prima l’occhio?'), t2('Where will people see this, and how big?', 'Dove lo vedranno le persone, e quanto grande?'), t2('If a friend glanced for one second, what would they remember?', 'Se un’amica o un amico lo guardasse per un secondo, cosa ricorderebbe?')] },
  Writing: { m: [
    m('Mission 001 · mirror selfie', 'Missione 001 · selfie allo specchio', ['Rewrite a caption so friends reply', 'Riscrivi una caption perché gli amici rispondano'], ['3 likes, 0 comments on Camilla’s gym selfie. Write the text under it so friends reply.', '3 like, 0 commenti sul selfie in palestra di Camilla. Scrivi il testo sotto la foto perché gli amici rispondano.']),
    m('Mission 002 · notification', 'Missione 002 · notifica', ['Write a kind reminder for Leo', 'Scrivi un promemoria gentile per Leo'], ['Leo hasn’t opened his language app in 3 days. Write a kind reminder, 10 words at most.', 'Leo non apre la sua app di lingue da 3 giorni. Scrivi un promemoria gentile, al massimo 10 parole.']),
    m('Mission 003 · birthday text', 'Missione 003 · messaggio di auguri', ['Write one birthday message three ways', 'Scrivi un messaggio di auguri in tre modi'], ['Elisa turns 28 tomorrow. Write her message three ways: funny, warm and tiny.', 'Elisa compie 28 anni domani. Scrivi il suo messaggio in tre modi: divertente, affettuoso e minuscolo.']),
    m('Mission 004 · laundry bio', 'Missione 004 · bio della lavanderia', ['Rewrite a bio that says nothing', 'Riscrivi una bio che non dice niente'], ['Bolla Laundry’s bio could be about any laundry. Rewrite it for students new in town.', 'La bio della Lavanderia Bolla potrebbe parlare di qualsiasi lavanderia. Riscrivila per chi studia ed è appena arrivato in città.']),
    m('Mission 005 · ticket comment', 'Missione 005 · commento sul biglietto', ['Reply to a rude comment', 'Rispondi a un commento maleducato'], ['Cinema Orsa raised tickets by €1 and someone is angry. Reply calmly.', 'Cinema Orsa ha alzato il biglietto di 1 € e qualcuno è arrabbiato. Rispondi con calma.']),
    m('Mission 006 · gelato name', 'Missione 006 · nome del gelato', ['Name a new flavour', 'Dai un nome a un gusto nuovo'], ['Pigro Gelato has a new flavour and no name. Give it one, plus a short sign for the counter.', 'Pigro Gelato ha un gusto nuovo e nessun nome. Daglielo, con un cartello breve per il banco.']),
  ], idea: t2('Your idea: a caption that opens with the thing that almost went wrong.', 'La tua idea: una caption che parte da quello che stava per andare storto.'), qs: [t2('Which word could you cut and lose nothing?', 'Quale parola potresti togliere senza perdere niente?'), t2('Who reads it, and what should they do next?', 'Chi lo legge, e cosa dovrebbe fare dopo?'), t2('If someone you know read this first, what would they ask?', 'Se lo leggesse prima qualcuno che ti conosce, cosa chiederebbe?')] },
  Code: { m: [
    m('Mission 001 · sold-out button', 'Missione 001 · pulsante esaurito', ['Fix the button that stays green', 'Sistema il pulsante che resta verde'], ['The Moss Merch hoodies sold out, but the Buy button stays green. One word in the code is spelled wrong.', 'Le felpe di Moss Merch sono finite, ma il pulsante Compra resta verde. Una parola nel codice è scritta male.']),
    m('Mission 002 · pizza quiz', 'Missione 002 · quiz della pizza', ['Write rules for a pizza quiz', 'Scrivi le regole di un quiz sulla pizza'], ['Pizzeria Zeta’s quiz has two questions and three pizzas. Every person must get exactly one.', 'Il quiz di Pizzeria Zeta ha due domande e tre pizze. Ogni persona deve riceverne una sola.']),
    m('Mission 003 · chat rule', 'Missione 003 · regola della chat', ['Find the trick, fix the rule', 'Trova il trucco, correggi la regola'], ['The last to reply to “cinema tonight?” pays for the tickets. Find a trick to avoid paying, then fix the rule.', 'Chi risponde per ultimo a “cinema stasera?” paga i biglietti. Trova un trucco per non pagare, poi correggi la regola.']),
    m('Mission 004 · promo code', 'Missione 004 · codice sconto', ['Fix a discount that costs more', 'Sistema uno sconto che fa pagare di più'], ['Dado Games’ 10% discount makes a 40 euro basket cost 44. One formula is wrong.', 'Lo sconto del 10% di Dado Games fa costare 44 euro un carrello da 40. Una formula è sbagliata.']),
    m('Mission 005 · “price?” reply', 'Missione 005 · risposta a “prezzo?”', ['Write an auto-reply for “price?”', 'Scrivi una risposta automatica a “prezzo?”'], ['Sunny Plants gets many DMs (private messages) that just say “price?”. Write rules for an automatic reply.', 'Sunny Plants riceve tanti DM (messaggi privati) che dicono solo “prezzo?”. Scrivi le regole di una risposta automatica.']),
    m('Mission 006 · basil robot', 'Missione 006 · robot e basilico', ['Write steps a robot can follow', 'Scrivi passaggi che un robot sa seguire'], ['Nico, your neighbour, waters your basil tomorrow. Write steps so exact that nothing can go wrong.', 'Domani Nico, il tuo vicino, innaffia il basilico. Scrivi passaggi così precisi che nulla possa andare storto.']),
  ], idea: t2('Your idea: a tiny rule for my group chat that picks who chooses the restaurant.', 'La tua idea: una piccola regola per la chat di gruppo che decide chi sceglie il ristorante.'), qs: [t2('What did you expect to happen, and what happened instead?', 'Cosa ti aspettavi che succedesse, e cosa è successo invece?'), t2('What should it do when something happens that you did not plan for?', 'Cosa dovrebbe fare quando succede qualcosa che non avevi previsto?'), t2('How would someone try to trick it?', 'Come proverebbe qualcuno a ingannarla?')] },
  Video: { m: [
    m('Mission 001 · toastie clip', 'Missione 001 · clip toast', ['Keep the best 6 seconds', 'Tieni i 6 secondi migliori'], ['Rocco’s 15-second clip starts slowly. Keep only the best seconds, 6 at most.', 'La clip di 15 secondi di Rocco parte piano. Tieni solo i secondi migliori, 6 al massimo.']),
    m('Mission 002 · missing speaker', 'Missione 002 · cassa sparita', ['Plan a funny 10-second clip', 'Pianifica una clip comica di 10 secondi'], ['Your speaker is gone and your cousin looks too innocent. Plan it in 3 shots.', 'La tua cassa è sparita e tua cugina sembra fin troppo innocente. Pianificala in 3 inquadrature.']),
    m('Mission 003 · awkward-moment clip', 'Missione 003 · clip figuraccia', ['Interview someone about an awkward moment', 'Intervista qualcuno su una figuraccia'], ['A 20-second clip, one phone. You ask 3 questions, someone tells the story.', 'Una clip di 20 secondi, un telefono. Tu fai 3 domande, un’altra persona racconta.']),
    m('Mission 004 · bike-shop subtitles', 'Missione 004 · sottotitoli ciclofficina', ['Turn tiny text into readable subtitles', 'Trasforma un testo minuscolo in sottotitoli leggibili'], ['Many people watch with the sound off. Split one block of tiny text into subtitles.', 'Molti guardano senza audio. Dividi un blocco di testo minuscolo in sottotitoli.']),
    m('Mission 005 · skate commentary', 'Missione 005 · telecronaca skate', ['Give a skate clip sports commentary', 'Fai la telecronaca di una clip di skate'], ['A 10-second skateboard clip. Write what a sports commentator would say over each shot.', 'Una clip di 10 secondi con uno skate. Scrivi cosa direbbe un telecronista sportivo su ogni inquadratura.']),
    m('Mission 006 · comment reply', 'Missione 006 · video risposta', ['Answer a comment with a video', 'Rispondi a un commento con un video'], ['A customer says the haircut costs too much. Plan a calm 12-second reply.', 'Un cliente dice che il taglio costa troppo. Pianifica una risposta calma di 12 secondi.']),
  ], idea: t2('Your idea: a 10-second clip that opens on the best moment, not on the walk to the shop.', 'La tua idea: una clip di 10 secondi che apre sul momento migliore, non sull’arrivo al negozio.'), qs: [t2('What does a stranger see first, and would they stay?', 'Cosa vede per primo uno sconosciuto, e resterebbe?'), t2('What is the one moment people would replay?', 'Qual è l’unico momento che la gente rivedrebbe?'), t2('What would the other person change, and why?', 'Cosa cambierebbe l’altra persona, e perché?')] },
  Selling: { m: [
    m('Mission 001 · used-lamp listing', 'Missione 001 · annuncio lampada usata', ['Fix “used lamp, €10”', 'Sistema “lampada usata, 10 euro”'], ['Three weeks on Subito, zero messages. Write the listing that makes a buyer write.', 'Tre settimane su Subito, zero messaggi. Scrivi l’annuncio che fa scrivere chi compra.']),
    m('Mission 002 · hot sauce', 'Missione 002 · salsa piccante', ['Script a 15-second hot sauce video', 'Scrivi il video da 15 secondi di una salsa piccante'], ['Ardi wants a real person on a phone, not a polished ad. Write what you say.', 'Ardi cerca una persona vera con il telefono, non uno spot patinato. Scrivi cosa dici.']),
    m('Mission 003 · denim jacket haggle', 'Missione 003 · trattativa giacca di jeans', ['Haggle without giving in', 'Tratta senza cedere'], ['Someone wants a €45 denim jacket for €30. Don’t give in, and stay friendly.', 'Qualcuno vuole una giacca di jeans da 45 € per 30 €. Non cedere subito, resta gentile.']),
    m('Mission 004 · candle DM', 'Missione 004 · DM delle candele', ['Rewrite a DM that sounds like spam', 'Riscrivi un DM che sembra spam'], ['Cera Cera’s DM to Sara got no reply. Make it sound like a person wrote it.', 'Il DM di Cera Cera a Sara non ha avuto risposta. Fallo sembrare scritto da una persona.']),
    m('Mission 005 · sticker or postcard poll', 'Missione 005 · sondaggio adesivi o cartoline', ['Test what people would pay for', 'Capisci cosa pagherebbero'], ['Gnomo Prints has two €8 product ideas. Get a first hint of which one people would pay for.', 'Gnomo Prints ha due idee di prodotto da 8 €. Cerca un primo indizio su quale pagherebbero.']),
    m('Mission 006 · silent buyer', 'Missione 006 · chi non risponde', ['Answer “Is it still available?”', 'Rispondi a “È ancora disponibile?”'], ['One short question arrives, then silence. Write the reply that keeps the chat alive.', 'Arriva una sola domanda, poi silenzio. Scrivi la risposta che tiene viva la chat.']),
  ], idea: t2('Your idea: sell my old backpack by saying the stuck zip first, then why €15 is fair.', 'La tua idea: vendere il mio vecchio zaino dicendo prima la cerniera che si blocca, poi perché 15 € sono giusti.'), qs: [t2('What would make the other person hesitate?', 'Che cosa farebbe esitare l’altra persona?'), t2('What does the person on the other side already want?', 'Che cosa vuole già la persona dall’altra parte?'), t2('What would they ask that you can’t answer yet?', 'Cosa ti chiederebbero a cui non sai ancora rispondere?')] },
  Music: { m: [
    m('Mission 001 · get-ready playlist', 'Missione 001 · playlist per prepararsi', ['Cut the song that kills the mood', 'Togli la canzone che rovina tutto'], ['Noa’s friends arrive at 9 tonight. One song kills the mood. Fix the order.', 'Gli amici di Noa arrivano stasera alle 21. Una canzone rovina l’atmosfera. Sistema l’ordine.']),
    m('Mission 002 · Monday reel, Forno Gufo', 'Missione 002 · reel del lunedì, Forno Gufo', ['Pick the drop for Monday', 'Scegli il drop del lunedì'], ['Forno Gufo opens its roller shutter at 6. Choose a 10-second sound and where the beat comes in.', 'Forno Gufo alza la saracinesca alle 6. Scegli un suono di 10 secondi e dove entra il ritmo.']),
    m('Mission 003 · Ilaria’s rough day', 'Missione 003 · la giornata storta di Ilaria', ['Reply to a rough-day text', 'Rispondi a un messaggio da giornata storta'], ['Ilaria had a terrible day. Say three lines out loud and pick one song.', 'Ilaria ha avuto una giornata terribile. Dille tre righe a voce e scegli una canzone.']),
    m('Mission 004 · Libro Lento playlist', 'Missione 004 · playlist di Libro Lento', ['Rename a playlist nobody taps', 'Rinomina una playlist che nessuno apre'], ['“Shelf mix 3” has 12 followers. Give it a name and a cover anyone taps.', '“Shelf mix 3” ha 12 follower. Dalle un nome e una cover che chiunque apre.']),
    m('Mission 005 · Clank Gym beat', 'Missione 005 · ritmo per Clank Gym', ['Tap a beat for a gym', 'Batti un ritmo per una palestra'], ['Clank Gym needs a 4-bar beat for its reels. Write it as a grid you can tap.', 'Clank Gym vuole un ritmo di 4 battute per i suoi reel. Scrivilo come griglia da battere.']),
    m('Mission 006 · Tiny Pan hook', 'Missione 006 · hook per Tiny Pan', ['Write a hook, take turns', 'Scrivi un hook, a turno'], ['Tiny Pan cooks in a student room. Write its 4-line hook, two lines each.', 'Tiny Pan cucina in una stanza da studente. Scrivi il suo hook di 4 righe, due righe a testa.']),
  ], idea: t2('Your idea: a 2-second sound for the moment a package arrives.', 'La tua idea: un suono di 2 secondi per il momento in cui arriva un pacco.'), qs: [t2('What would make someone skip or scroll past it?', 'Cosa spingerebbe qualcuno a saltarla o a scorrere oltre?'), t2('Who is listening, and where are they?', 'Chi sta ascoltando, e dove si trova?'), t2('What would someone else hear in it that you cannot?', 'Cosa ci sentirebbe un’altra persona che tu non senti?')] },
  Prompting: { m: [
    m('Mission 001 · pottery post', 'Missione 001 · post del laboratorio', ['Rewrite Dana’s prompt with her facts', 'Riscrivi il prompt di Dana con i suoi fatti'], ['A prompt is what you type to an AI. Dana’s was one line, so the post came out boring.', 'Il prompt è quello che scrivi a un’AI. Quello di Dana era di una riga, così il post è uscito noioso.']),
    m('Mission 002 · exam quiz', 'Missione 002 · quiz per l’esame', ['Get an AI to quiz Sofia', 'Fai interrogare Sofia da un’AI'], ['Sofia rereads her notes and nothing sticks. Write the prompt that makes the AI test her.', 'Sofia rilegge gli appunti e non le resta niente. Scrivi il prompt che porta l’AI a interrogarla.']),
    m('Mission 003 · surprise dinner', 'Missione 003 · cena a sorpresa', ['Plan Giulia’s dinner with one prompt', 'Organizza la cena di Giulia con un prompt'], ['Giulia turns 25 on Saturday. Give the AI the facts it needs, so it does not have to guess.', 'Giulia compie 25 anni sabato. Dai all’AI i fatti che le servono, così non deve tirare a indovinare.']),
    m('Mission 004 · closing time', 'Missione 004 · orario di chiusura', ['Stop an AI from inventing answers', 'Impedisci a un’AI di inventare risposte'], ['The AI sounded sure and was wrong. Change the prompt so it admits what it doesn’t know.', 'L’AI sembrava sicura e sbagliava. Cambia il prompt perché ammetta quello che non sa.']),
    m('Mission 005 · flat bills', 'Missione 005 · spese di casa', ['Turn messy bills into a table', 'Trasforma spese confuse in una tabella'], ['Four flatmates, messy payments. Ask an AI for a table of who owes what.', 'Quattro coinquilini, pagamenti in disordine. Chiedi a un’AI una tabella di chi deve cosa.']),
    m('Mission 006 · two flats', 'Missione 006 · due case', ['Help a friend pick a flat', 'Aiuta una persona a scegliere casa'], ['Two flats, one choice. Write the prompt around what matters to your friend, not to you.', 'Due case, una scelta. Scrivi il prompt su ciò che conta per l’altra persona, non per te.']),
  ], idea: t2('Your idea: a prompt that makes the AI ask me three questions before it answers.', 'La tua idea: un prompt che fa fare all’AI tre domande prima di rispondere.'), qs: [t2('What did you tell the AI that it could not have guessed?', 'Cosa hai detto all’AI che non poteva indovinare?'), t2('What would you check before trusting the answer?', 'Cosa controlleresti prima di fidarti della risposta?'), t2('If someone else used your prompt, would they get the same answer?', 'Se un’altra persona usasse il tuo prompt, otterrebbe la stessa risposta?')] },
};
Object.setPrototypeOf(FIELDS, null);
