import { t2 } from './i18n';

const small = t2('What is the smallest version you could finish today?', 'Qual è la versione più piccola che potresti finire oggi?');
const avoid = t2('Which part are you avoiding, and why?', 'Quale parte stai evitando, e perché?');
const m = (n: string, it: string, title: [string, string], blurb: [string, string]) => [t2(n, it), t2(title[0], title[1]), t2(blurb[0], blurb[1])];
// Concrete briefs for each mission live in missions.ts (MX), same field and index.
// Null prototype (set below) so FIELDS[key] is a safe check for keys from URLs or storage, even "__proto__".
export const FIELDS: Record<string, { m: string[][]; idea: string; qs: string[] }> = {
  Design: { m: [
    m('Mission 001 · crowded story', 'Missione 001 · storia strapiena', ['Fix a story that shouts', 'Aggiusta una storia che urla'], ['7 things on one story. People swipe past in a second.', '7 cose in una sola storia. La gente scorre via in un secondo.']),
    m('Mission 002 · bar sticker', 'Missione 002 · adesivo del bar', ['Make a sticker for the corner bar', 'Crea un adesivo per il bar sotto casa'], ['Bar Ficus has no logo. Rosa wants a sticker for the door.', 'Bar Ficus non ha un logo. Rosa vuole un adesivo per la porta.']),
    m('Mission 003 · dream room', 'Missione 003 · stanza dei sogni', ['Plan a dream-room moodboard', 'Pianifica il moodboard di una stanza dei sogni'], ['One sentence, one bare room. Show Elena the feeling in 6 pictures.', 'Una frase, una stanza vuota. Mostra a Elena la sensazione in 6 immagini.']),
    m('Mission 004 · sneaker photo', 'Missione 004 · foto delle sneaker', ['Rescue a dark sneaker photo', 'Salva una foto buia di sneaker'], ['No messages in 5 days. The shoes are fine. The photo is the problem.', 'Nessun messaggio in 5 giorni. Le scarpe vanno bene. Il problema è la foto.']),
    m('Mission 005 · swipe cover', 'Missione 005 · copertina del carosello', ['Make a cover that makes people swipe', 'Crea una copertina che fa scorrere'], ['5 good tips and no first picture yet. Make people want the next one.', '5 buoni consigli e ancora nessuna prima immagine. Fai venire voglia di vedere la prossima.']),
    m('Mission 006 · two thumbnails', 'Missione 006 · due miniature', ['Two thumbnails, one winner', 'Due miniature, una vincente'], ['One video, two thumbnails. Whichever gets tapped more wins.', 'Un video, due miniature. Vince quella su cui si tocca di più.']),
  ], idea: t2('Your idea: a poster for Friday’s flat dinner, with one big word, red letters on cream paper and a tiny drawn fork.', 'La tua idea: un poster per la cena di venerdì in casa, con una sola parola grande, lettere rosse su carta crema e una piccola forchetta disegnata.'), qs: [t2('What does the eye land on first?', 'Su cosa cade prima l’occhio?'), t2('Where will people see this, and how big?', 'Dove lo vedranno le persone, e quanto grande?'), t2('If a friend glanced for one second, what would they remember?', 'Se un’amica o un amico lo guardasse per un secondo, cosa ricorderebbe?')] },
  Writing: { m: [
    m('Mission 001 · mirror selfie', 'Missione 001 · selfie allo specchio', ['Fix a flat caption', 'Sistema una caption piatta'], ['3 likes, 0 comments. Give Camilla’s mirror selfie a caption people answer.', '3 like, 0 commenti. Dai al selfie di Camilla una caption a cui rispondere.']),
    m('Mission 002 · notification', 'Missione 002 · notifica', ['A message that doesn’t nag', 'Un messaggio che non assilla'], ['Parlo wants Leo back after 3 quiet days. Say it kindly, in 10 words.', 'Parlo vuole che Leo torni dopo 3 giorni senza aprire l’app. Dillo con gentilezza, in 10 parole.']),
    m('Mission 003 · birthday text', 'Missione 003 · messaggio di auguri', ['Birthday message, three tones', 'Auguri in tre toni'], ['Elisa turns 28 tomorrow. Write the message three ways and keep the best.', 'Elisa compie 28 anni domani. Scrivi il messaggio in tre modi e tieni il migliore.']),
    m('Mission 004 · laundry bio', 'Missione 004 · bio della lavanderia', ['Fix a bio that says nothing', 'Sistema una bio che non dice niente'], ['Bolla Laundry’s bio fits any laundry. Make a new student want to walk in.', 'La bio della Lavanderia Bolla va bene per qualsiasi lavanderia. Fai venire voglia di entrare a chi studia ed è appena arrivato in città.']),
    m('Mission 005 · ticket comment', 'Missione 005 · commento sul biglietto', ['Reply to a rude comment', 'Rispondi a un commento maleducato'], ['Cinema Orsa raised tickets by €1 and someone is angry. Reply calmly.', 'Cinema Orsa ha alzato il biglietto di 1 € e qualcuno è arrabbiato. Rispondi con calma.']),
    m('Mission 006 · gelato name', 'Missione 006 · nome del gelato', ['Name a new flavour', 'Dai un nome a un gusto nuovo'], ['Pigro Gelato has a new flavour and no name. Name it, then sell it in one line.', 'Pigro Gelato ha un gusto nuovo e nessun nome. Dagli un nome, poi vendilo in una riga.']),
  ], idea: t2('Your idea: a caption that opens with the thing that almost went wrong.', 'La tua idea: una caption che parte da quello che stava per andare storto.'), qs: [t2('Which word could you cut and lose nothing?', 'Quale parola potresti togliere senza perdere niente?'), t2('Who reads it, and what should they do next?', 'Chi lo legge, e cosa dovrebbe fare dopo?'), t2('If someone you know read this first, what would they ask?', 'Se lo leggesse prima qualcuno che ti conosce, cosa chiederebbe?')] },
  Code: { m: [
    m('Mission 001 · sold-out button', 'Missione 001 · pulsante esaurito', ['Make the button turn red', 'Fai diventare rosso il pulsante'], ['The Moss Merch hoodies sold out, but the Buy button stays green. One word is off.', 'Le felpe di Moss Merch sono esaurite, ma il pulsante Compra resta verde. Una parola è sbagliata.']),
    m('Mission 002 · pizza quiz', 'Missione 002 · quiz della pizza', ['Write a “which pizza are you?” quiz', 'Scrivi un quiz “che pizza sei?”'], ['Pizzeria Zeta wants a story quiz: two questions, three pizzas, nobody left without a result.', 'Pizzeria Zeta vuole un quiz per le storie: due domande, tre pizze, nessuno senza risultato.']),
    m('Mission 003 · chat rule', 'Missione 003 · regola della chat', ['Break a group-chat rule', 'Rompi la regola di una chat di gruppo'], ['The last to reply to “cinema tonight?” pays for the tickets. Find the trick that dodges it, then close the gap.', 'Chi risponde per ultimo a “cinema stasera?” paga i biglietti. Trova il trucco per non pagare, poi chiudi il buco.']),
    m('Mission 004 · promo code', 'Missione 004 · codice sconto', ['Fix a promo code that charges more', 'Sistema un codice sconto che fa pagare di più'], ['Dado Games’ “10% off” code makes a basket cost more. One formula is off.', 'Il codice “10% di sconto” di Dado Games fa costare di più un carrello. Una formula è sbagliata.']),
    m('Mission 005 · “price?” reply', 'Missione 005 · risposta a “prezzo?”', ['Write an auto-reply for “price?”', 'Scrivi una risposta automatica a “prezzo?”'], ['Every photo Sunny Plants posts gets a DM that just says “price?”. Teach a bot to answer well.', 'Ogni foto che Sunny Plants pubblica riceve un DM che dice solo “prezzo?”. Insegna a un bot a rispondere bene.']),
    m('Mission 006 · basil robot', 'Missione 006 · robot e basilico', ['Write steps a robot can follow', 'Scrivi passaggi che un robot sa seguire'], ['Nico, your neighbour, waters your basil tomorrow. Write steps so exact that nothing can go wrong.', 'Domani Nico, il tuo vicino, innaffia il basilico. Scrivi passaggi così precisi che nulla possa andare storto.']),
  ], idea: t2('Your idea: a tiny rule for my group chat that picks who chooses the restaurant.', 'La tua idea: una piccola regola per la chat di gruppo che decide chi sceglie il ristorante.'), qs: [t2('What did you expect to happen, and what happened instead?', 'Cosa ti aspettavi che succedesse, e cosa è successo invece?'), t2('What should it do when something happens that you did not plan for?', 'Cosa dovrebbe fare quando succede qualcosa che non avevi previsto?'), t2('How would someone try to trick it?', 'Come proverebbe qualcuno a ingannarla?')] },
  Video: { m: [
    m('Mission 001 · toastie clip', 'Missione 001 · clip toast', ['Open on the best moment', 'Apri sul momento migliore'], ['A 30-second toastie clip. Nobody gets past the walk to the van.', 'Una clip da 30 secondi su un toast. Nessuno supera l’arrivo al furgone.']),
    m('Mission 002 · speaker POV', 'Missione 002 · POV cassa', ['POV: the speaker is gone', 'POV: la cassa è sparita'], ['Plan a 10-second skit about a cousin and a missing speaker.', 'Pianifica una scenetta di 10 secondi su una cugina e una cassa sparita.']),
    m('Mission 003 · worst-job clip', 'Missione 003 · clip peggior lavoro', ['Direct a worst-job story', 'Dirigi la storia del peggior lavoro'], ['20 seconds, one phone. You stand behind it and ask the questions.', '20 secondi, un telefono. Tu stai dietro e fai le domande.']),
    m('Mission 004 · bike-workshop captions', 'Missione 004 · sottotitoli ciclofficina', ['Make the captions readable', 'Rendi leggibili i sottotitoli'], ['Lots of people watch with the sound off. Fix one wall of tiny text.', 'Molti guardano senza audio. Sistema un muro di testo minuscolo.']),
    m('Mission 005 · skate commentary', 'Missione 005 · telecronaca skate', ['Commentate on a skateboard push', 'Fai la telecronaca di una spinta su skate'], ['Write what a sports commentator would say over a 10-second skateboard clip.', 'Scrivi cosa direbbe un telecronista sportivo su una clip di 10 secondi con uno skate.']),
    m('Mission 006 · comment reply', 'Missione 006 · video risposta', ['Answer a comment with a video', 'Rispondi a un commento con un video'], ['A customer says the haircut costs too much. Plan a calm 12-second reply.', 'Un cliente dice che il taglio costa troppo. Pianifica una risposta calma di 12 secondi.']),
  ], idea: t2('Your idea: a 10-second clip that opens on the best moment, not on the walk to the shop.', 'La tua idea: una clip di 10 secondi che apre sul momento migliore, non sull’arrivo al negozio.'), qs: [t2('What does a stranger see first, and would they stay?', 'Cosa vede per primo uno sconosciuto, e resterebbe?'), t2('What is the one moment people would replay?', 'Qual è l’unico momento che la gente rivedrebbe?'), t2('What would the other person change, and why?', 'Cosa cambierebbe l’altra persona, e perché?')] },
  Selling: { m: [
    m('Mission 001 · used-lamp listing', 'Missione 001 · annuncio lampada usata', ['Fix “used lamp, €10”', 'Sistema “lampada usata, 10 euro”'], ['Three weeks on Subito, zero messages. Write the listing that makes a buyer write.', 'Tre settimane su Subito, zero messaggi. Scrivi l’annuncio che fa scrivere chi compra.']),
    m('Mission 002 · hot sauce', 'Missione 002 · salsa piccante', ['Script a 15-second hot sauce video', 'Scrivi il video da 15 secondi di una salsa piccante'], ['Ardi wants a real person on a phone, not a polished ad. Write what you say.', 'Ardi cerca una persona vera con il telefono, non uno spot patinato. Scrivi cosa dici.']),
    m('Mission 003 · denim jacket haggle', 'Missione 003 · trattativa giacca di jeans', ['Haggle without caving', 'Tratta senza cedere'], ['Someone wants a €45 denim jacket for €30. Don’t cave, and stay friendly.', 'Qualcuno vuole una giacca di jeans da 45 € per 30 €. Non cedere subito, resta gentile.']),
    m('Mission 004 · candle DM', 'Missione 004 · DM delle candele', ['Rewrite a DM that sounds like spam', 'Riscrivi un DM che sembra spam'], ['Cera Cera’s DM to Sara got no reply. Make it sound like a person wrote it.', 'Il DM di Cera Cera a Sara non ha avuto risposta. Fallo sembrare scritto da una persona.']),
    m('Mission 005 · sticker or postcard poll', 'Missione 005 · sondaggio adesivi o cartoline', ['Test what people would pay for', 'Capisci cosa pagherebbero'], ['Gnomo Prints has two €8 product ideas. Get a first hint of which one people would pay for.', 'Gnomo Prints ha due idee di prodotto da 8 €. Cerca un primo indizio su quale pagherebbero.']),
    m('Mission 006 · silent buyer', 'Missione 006 · chi non risponde', ['Answer “Is it still available?”', 'Rispondi a “È ancora disponibile?”'], ['One short question arrives, then silence. Write the reply that keeps the chat alive.', 'Arriva una sola domanda, poi silenzio. Scrivi la risposta che tiene viva la chat.']),
  ], idea: t2('Your idea: sell my old backpack by saying the stuck zip first, then why €15 is fair.', 'La tua idea: vendere il mio vecchio zaino dicendo prima la cerniera che si blocca, poi perché 15 € sono giusti.'), qs: [t2('What would make the other person hesitate?', 'Che cosa farebbe esitare l’altra persona?'), t2('What does the person on the other side already want?', 'Che cosa vuole già la persona dall’altra parte?'), t2('What would they ask that you can’t answer yet?', 'Cosa ti chiederebbero a cui non sai ancora rispondere?')] },
  Music: { m: [
    m('Mission 001 · get-ready playlist', 'Missione 001 · playlist per prepararsi', ['Cut the vibe killer', 'Togli la canzone che rovina tutto'], ['Noa’s friends arrive at 9 tonight. One song kills the mood. Fix the order.', 'Gli amici di Noa arrivano stasera alle 21. Una canzone rovina l’atmosfera. Sistema l’ordine.']),
    m('Mission 002 · Monday reel, Forno Gufo', 'Missione 002 · reel del lunedì, Forno Gufo', ['Pick the drop for Monday', 'Scegli il drop del lunedì'], ['Forno Gufo opens its roller shutter at 6. Choose a 10-second sound and where the beat kicks in.', 'Forno Gufo alza la saracinesca alle 6. Scegli un suono di 10 secondi e dove entra il ritmo.']),
    m('Mission 003 · Ilaria’s rough day', 'Missione 003 · la giornata storta di Ilaria', ['Reply to a rough-day text', 'Rispondi a un messaggio da giornata storta'], ['Ilaria had a terrible day. Say three lines out loud and pick one song.', 'Ilaria ha avuto una giornata terribile. Dille tre righe a voce e scegli una canzone.']),
    m('Mission 004 · Libro Lento playlist', 'Missione 004 · playlist di Libro Lento', ['Rename a playlist nobody taps', 'Rinomina una playlist che nessuno apre'], ['“Shelf mix 3” has 12 followers. Give it a name and a cover anyone taps.', '“Shelf mix 3” ha 12 follower. Dalle un nome e una cover che chiunque apre.']),
    m('Mission 005 · Clank Gym beat', 'Missione 005 · ritmo per Clank Gym', ['Tap a beat for a gym', 'Batti un ritmo per una palestra'], ['Clank Gym needs a 4-bar beat for its reels. Write it as a grid you can tap.', 'Clank Gym vuole un ritmo di 4 battute per i suoi reel. Scrivilo come griglia da battere.']),
    m('Mission 006 · Tiny Pan hook', 'Missione 006 · hook per Tiny Pan', ['Write a hook, take turns', 'Scrivi un hook, a turno'], ['Tiny Pan cooks in a student room. Write its 4-line hook, two lines each.', 'Tiny Pan cucina in una stanza da studente. Scrivi il suo hook di 4 righe, due righe a testa.']),
  ], idea: t2('Your idea: a 2-second sound for the moment a package arrives.', 'La tua idea: un suono di 2 secondi per il momento in cui arriva un pacco.'), qs: [t2('What would make someone skip or scroll past it?', 'Cosa spingerebbe qualcuno a saltarla o a scorrere oltre?'), t2('Who is listening, and where are they?', 'Chi sta ascoltando, e dove si trova?'), t2('What would someone else hear in it that you cannot?', 'Cosa ci sentirebbe un’altra persona che tu non senti?')] },
};
Object.setPrototypeOf(FIELDS, null);
