import { t2 } from './i18n';

// Per mission (same field and index as missions.ts): one worked example of a strong answer, and three hints that go
// from broad to specific. Hints are always questions: KERN.AI asks, it never answers for you.
export type Help = { ex: string; hints: string[] };
const h = (ex: [string, string], a: [string, string], b: [string, string], c: [string, string]): Help => ({
  ex: t2(...ex), hints: [t2(...a), t2(...b), t2(...c)],
});

export const HELPS: Record<string, Help[]> = {
  Design: [
    h(['Keep: “Saturday · 2 for 1 pizza till 9”. Cut: DJ, new menu, contest, tag 3 friends, the address (it goes in a second story). The photo stays, darker at the bottom so the words read. One colour: cream letters, big, on that dark part. The dog stays if it makes you stop: your call. A tiny “Pomo Pizza” under the words.', 'Tengo: “Sabato · 2x1 sulle pizze fino alle 21”. Tolgo: DJ, nuovo menu, concorso, tagga 3 amici, l’indirizzo (va in una seconda storia). La foto resta, più scura in basso perché le parole si leggano. Un colore: lettere crema, grandi, sulla parte scura. Il cane resta se ti fa fermare: decidi tu. Un piccolo “Pomo Pizza” sotto le parole.'],
      ['If a stranger only has one second, what should they read?', 'Se uno sconosciuto ha solo un secondo, cosa deve leggere?'],
      ['Which of the 7 things could wait for a second story?', 'Quali delle 7 cose possono aspettare una seconda storia?'],
      ['Which one colour makes the words jump off the background?', 'Quale colore fa saltare fuori le parole dallo sfondo?']),
    h(['Picture: a fat green leaf with a steam swirl, like a plant that drinks espresso. Colours: dark green and cream. Name “Bar Ficus” in round letters. Line: “Sit down, tesoro.”', 'Immagine: una grossa foglia verde con una voluta di vapore, come una pianta che beve espresso. Colori: verde scuro e crema. Nome “Bar Ficus” in lettere tonde. Frase: “Siediti, tesoro.”'],
      ['What would a regular say if you asked what this bar is like?', 'Cosa direbbe un cliente fisso se gli chiedessi com’è questo bar?'],
      ['Which fact on the list could be drawn as one simple shape?', 'Quale fatto dell’elenco si può disegnare con una forma semplice?'],
      ['Which 2 colours stay clear on a glass door in daylight?', 'Quali 2 colori restano chiari su una porta a vetri di giorno?']),
    h(['Feeling: slow, salty. 1) a thin white curtain moving in the wind 2) warm lamp light on a plain wall 3) a chipped blue cup on a windowsill 4) a pile of old paperbacks 5) a striped blanket 6) shells in a bowl. Colours: white and sea blue.', 'Sensazione: lenta, salata. 1) una tenda bianca leggera mossa dal vento 2) la luce calda di una lampada su un muro 3) una tazza blu scheggiata sul davanzale 4) una pila di vecchi tascabili 5) una coperta a righe 6) conchiglie in una ciotola. Colori: bianco e blu mare.'],
      ['What does the sentence smell or sound like?', 'Che odore o suono ha la frase?'],
      ['What small thing in a room carries that feeling?', 'Quale piccola cosa in una stanza porta quella sensazione?'],
      ['Which 2 colours show up in most of your 6 pictures?', 'Quali 2 colori compaiono nella maggior parte delle tue 6 immagini?']),
    h(['Worst: dim yellow light, messy bed, toes cut off. Reshoot: by a window at midday, on a plain grey floor, shoes side by side, laces tied. Trim: shoes fill the frame, no hoodie. Photo 2: a close-up of the sole.', 'Peggio: luce gialla fioca, letto sfatto, punte tagliate. Nuovo scatto: vicino a una finestra a mezzogiorno, su un pavimento grigio liscio, scarpe affiancate, lacci allacciati. Ritaglio: le scarpe riempiono la foto, niente felpa. Foto 2: primo piano della suola.'],
      ['Which of these flaws would you notice first?', 'Quale di questi difetti noteresti per primo?'],
      ['Where in your home is the light best, and at what time?', 'Dove in casa c’è la luce migliore, e a che ora?'],
      ['What would make the shoes the only thing in the frame?', 'Cosa farebbe delle scarpe l’unica cosa nell’inquadratura?']),
    h(['Tip: label your food. Words: “Who ate the yogurt?” Picture: an open fridge, one lemon-yellow sticky note on a yogurt pot saying “MARTA’S”. Colours: lemon yellow and dark grey. The other 4 tips stay inside.', 'Consiglio: etichetta il tuo cibo. Parole: “Chi ha mangiato lo yogurt?” Immagine: un frigo aperto, un post-it giallo limone su un vasetto di yogurt con scritto “DI MARTA”. Colori: giallo limone e grigio scuro. Gli altri 4 consigli restano dentro.'],
      ['Which tip would a stranger most want the answer to?', 'Di quale consiglio uno sconosciuto vorrebbe di più la risposta?'],
      ['What could you show that makes someone ask why?', 'Cosa potresti mostrare che faccia chiedere perché?'],
      ['Which single bright colour still pops when the picture is small?', 'Quale colore acceso spicca ancora quando l’immagine è piccola?']),
    h(['A: Luca with eyes wide, holding up the orange wrapper. Words: “DAY 7?!” White letters on dark blue. B: Luca asleep on the table, orange wrappers all around. Words: “Day 7. Again.” Teal background. Winner: A, because the face asks a question.', 'A: Luca con gli occhi spalancati, che alza la confezione arancione. Parole: “GIORNO 7?!” Lettere bianche su blu scuro. B: Luca addormentato sul tavolo, confezioni arancioni tutto intorno. Parole: “Giorno 7. Ancora.” Sfondo verde acqua. Vince A, perché la faccia fa una domanda.'],
      ['What is the one question a stranger should ask?', 'Qual è l’unica domanda che uno sconosciuto dovrebbe farsi?'],
      ['What does Luca’s face say, and do the words agree?', 'Cosa dice la faccia di Luca, e le parole sono d’accordo?'],
      ['Which colour pops next to an orange wrapper?', 'Quale colore spicca accanto a una confezione arancione?']),
  ],
  Writing: [
    h(['Almost skipped today. Strap snapped on the bus. Lifted 40 kg anyway.', 'Allenamento quasi saltato. Tracolla rotta sul bus. 40 kg alzati comunque.'],
      ['What would Camilla tell a friend about this workout, in one breath?', 'Cosa racconterebbe Camilla di questo allenamento, tutto d’un fiato?'],
      ['Which of the three details would surprise a friend most?', 'Quale dei tre dettagli sorprenderebbe di più chi ti conosce?'],
      ['Which word in your caption does nothing?', 'Quale parola della tua caption non serve a niente?']),
    h(['Two minutes today? Your Spanish coffee order is waiting.', 'Due minuti oggi? Il tuo caffè in spagnolo ti aspetta.'],
      ['What could you say that makes Leo feel proud, not guilty?', 'Cosa potresti dire che faccia sentire Leo orgoglioso e non in colpa?'],
      ['Which real thing from Leo’s story belongs in the message?', 'Quale cosa vera della storia di Leo ci sta nel messaggio?'],
      ['Which word sounds like a sermon, not a friend?', 'Quale parola suona come una predica e non come un amico?']),
    h(['Funny: Happy birthday Elisa! Midnight pasta, as tradition says. Fritz gets a bite, we don’t discuss it. Warm: Elisa, two years of sharing a flat and you’re still my favourite person to be late with. Love you. Tiny: Happy birthday E! Be late, I’ll wait.', 'Divertente: Auguri Elisa! Pasta a mezzanotte, come da tradizione. A Fritz un assaggio, non ne parliamo. Calda: Elisa, due anni a dividere casa e sei ancora la persona con cui preferisco far tardi. Ti voglio bene. Minuscola: Auguri E! Fai pure tardi, ti aspetto.'],
      ['What does Elisa love that nobody else would mention?', 'Cosa ama Elisa che nessun altro nominerebbe?'],
      ['Which detail from the list makes you grin?', 'Quale dettaglio della lista ti fa sorridere?'],
      ['Which words can you cut from the tiny one and still sound like you?', 'Quali parole puoi togliere da quella minuscola e suonare ancora come te?']),
    h(['Laundry day, sorted. By the university gate: wash €4, dry €3, soap included. Open every day, even Sunday.', 'Bucato risolto. Vicino al cancello dell’università: lavaggio 4 €, asciugatura 3 €, sapone incluso. Aperti ogni giorno, anche la domenica.'],
      ['What would a student ask before carrying a bag of clothes here?', 'Cosa chiederebbe chi studia prima di portare qui un sacco di vestiti?'],
      ['Which words in the old bio fit any laundry?', 'Quali parole della vecchia bio vanno bene per qualsiasi lavanderia?'],
      ['Which three facts would you text a friend who just moved?', 'Quali tre fatti manderesti a chi si è appena trasferito?']),
    h(['Fair, €1 stings. Heating and film rental cost 25% more, our first rise in 4 years. Tuesdays stay €5, come say hi.', 'Capito, 1 € pesa. Riscaldamento e film costano il 25% in più, primo aumento in 4 anni. Il martedì resta 5 €, vieni a salutarci.'],
      ['What is the person really upset about, under the rude words?', 'Per cosa è davvero arrabbiato chi scrive, sotto le parole maleducate?'],
      ['What true fact would you say first if you stayed calm?', 'Quale fatto vero diresti per primo mantenendo la calma?'],
      ['Which word in your reply sounds defensive or sarcastic?', 'Quale parola della tua risposta suona difensiva o sarcastica?']),
    h(['Names: Salty Sunday / Hazel Nap / Lazy Ribbon. Pick: Hazel Nap. Sign: Roasted hazelnut, sea salt, chocolate ribbon. Eat it slowly, like us.', 'Nomi: Domenica salata / Pisolo di nocciola / Nastro pigro. Scelta: Pisolo di nocciola. Cartello: Nocciole tostate, sale marino, nastro di cioccolato. Mangialo piano, come noi.'],
      ['What would you say to a friend who asks what it tastes like?', 'Cosa diresti a chi ti chiede che sapore ha?'],
      ['Which word from the list could start a name?', 'Quale parola della lista potrebbe iniziare un nome?'],
      ['What would a lazy, kind shop say that no other shop would?', 'Cosa direbbe un locale pigro e gentile che nessun altro direbbe?']),
  ],
  Code: [
    h(['Found it: colour with a u on line 4. Everywhere else it is color. Fixed: if (hoodiesLeft === 0) color = "red";', 'Trovato: colour con la u alla riga 4. Altrove c’è color. Corretto: if (hoodiesLeft === 0) color = "red";'],
      ['Which line is supposed to change the button’s colour?', 'Quale riga dovrebbe cambiare il colore del pulsante?'],
      ['That line changes something. Is it the same thing the last line paints?', 'Quella riga cambia qualcosa. È la stessa cosa che l’ultima riga colora?'],
      ['Still stuck? What do you notice if you read lines 3 and 4 letter by letter?', 'Ancora niente? Cosa noti se leggi le righe 3 e 4 lettera per lettera?']),
    h(['IF spice is lots THEN Diavola. IF spice is none AND you stay in THEN Margherita. IF spice is none AND you go out THEN Quattro Formaggi.', 'SE piccante è tanto ALLORA Diavola. SE piccante è niente E resti a casa ALLORA Margherita. SE piccante è niente E esci ALLORA Quattro Formaggi.'],
      ['Which answers would make you think of a spicy pizza?', 'Quali risposte ti fanno pensare a una pizza piccante?'],
      ['Which pizza fits someone who stays in and wants no spice?', 'Quale pizza va a chi resta a casa e non vuole piccante?'],
      ['Which of your rules does someone who says “go out” and “lots” match?', 'Quali delle tue regole valgono per chi risponde “fuori” e “tanto”?']),
    h(['Ada’s trick: never reply, so she is never last. Fix: IF you have not replied by 20:30, THEN you pay. IF everyone has replied, THEN the last reply pays.', 'Il trucco di Ada: non rispondere mai, così non è mai l’ultima. Correzione: SE non hai risposto entro le 20:30, ALLORA paghi. SE hanno risposto tutti, ALLORA paga chi ha risposto per ultimo.'],
      ['Who could skip paying without breaking the rule?', 'Chi potrebbe non pagare senza violare la regola?'],
      ['What should the rule say about someone who never replies?', 'Cosa dovrebbe dire la regola su chi non risponde mai?'],
      ['What if two people never reply, or two reply in the same minute?', 'E se due persone non rispondono mai, o rispondono nello stesso minuto?']),
    h(['The sheet adds the 10% instead of taking it off: 40 + 4 = 44. Fixed: =B1-B1*B2 gives 36. A basket of 100 gives 90.', 'Il foglio aggiunge il 10% invece di toglierlo: 40 + 4 = 44. Corretta: =B1-B1*B2 dà 36. Un carrello da 100 dà 90.'],
      ['Should a discount code make the price go up or down?', 'Un codice sconto dovrebbe far salire o scendere il prezzo?'],
      ['In the formula, is the 10% part added or taken away?', 'Nella formula, la parte del 10% viene aggiunta o tolta?'],
      ['What does the formula give for a basket of 100, and what should it give?', 'Cosa dà la formula per un carrello da 100, e cosa dovrebbe dare?']),
    h(['IF the DM names a plant THEN reply: “The monstera is 42 euro.” IF it only says “price?” THEN ask: “Which one: fern, cactus or monstera?” IF it is anything else THEN reply: “Good question, we will answer this one ourselves today.”', 'SE il DM nomina una pianta ALLORA rispondi: “La monstera costa 42 euro.” SE dice solo “prezzo?” ALLORA chiedi: “Quale? Felce, cactus o monstera?” SE è qualcos’altro ALLORA rispondi: “Bella domanda, ti rispondiamo noi di persona oggi.”'],
      ['What does each DM really want to know?', 'Cosa vuole davvero sapere chi manda ogni DM?'],
      ['What should the bot do when it cannot tell which plant?', 'Cosa deve fare il bot quando non capisce di quale pianta si parla?'],
      ['Which rule should be checked first: the plant name or the word “price”?', 'Quale regola va controllata per prima: il nome della pianta o la parola “prezzo”?']),
    h(['DO: take the watering can from under the sink. DO: fill it halfway at the tap. IF the soil is dry, THEN REPEAT: pour a little water UNTIL water shows in the saucer, or you poured 5 times. DO: put the watering can back under the sink.', 'FAI: prendi l’annaffiatoio da sotto il lavandino. FAI: riempilo a metà al rubinetto. SE la terra è asciutta, ALLORA RIPETI: versa un po’ d’acqua FINCHÉ si vede acqua nel sottovaso, o hai versato 5 volte. FAI: rimetti l’annaffiatoio sotto il lavandino.'],
      ['What does Nico need to know that you take for granted?', 'Cosa deve sapere Nico che tu dai per scontato?'],
      ['What tells the robot to stop pouring?', 'Cosa dice al robot di smettere di versare?'],
      ['What if that never happens: how many pours is too many?', 'E se non succede mai: quante versate sono troppe?']),
  ],
  Video: [
    h(['9-11 the cheese stretch, 11-13 the first bite, eyes wide. 2 + 2 = 4 seconds. It opens on the cheese and nobody waits for anything.', '9-11 il formaggio che fila, 11-13 il primo morso, occhi spalancati. 2 + 2 = 4 secondi. Apre sul formaggio e nessuno aspetta niente.'],
      ['Which moment would you rewatch three times?', 'Quale momento riguarderesti tre volte?'],
      ['What could you drop without anyone missing it?', 'Cosa potresti togliere senza che nessuno lo noti?'],
      ['Do your pieces add up to 6 seconds or less?', 'I tuoi pezzi fanno 6 secondi o meno?']),
    h(['Shot 1 (0-3s): the shelf, empty, one loose cable. Text: “POV: your Zumo is gone.” Shot 2 (3-7s): slow turn to Bea on the sofa, music from under a cushion. Text: “Music. From a cushion.” Shot 3 (7-10s): she lifts the cushion: the speaker, charged. Text: “She even charged it.” 3 + 4 + 3 = 10.', 'Inquadratura 1 (0-3s): lo scaffale vuoto, un cavo penzolante. Testo: “POV: il tuo Zumo è sparito.” Inquadratura 2 (3-7s): giro lento su Bea sul divano, musica da sotto un cuscino. Testo: “Musica. Da sotto un cuscino.” Inquadratura 3 (7-10s): lei alza il cuscino: lo Zumo, carico. Testo: “L’ha pure caricato.” 3 + 4 + 3 = 10.'],
      ['What would you see first when you walk into that room?', 'Cosa vedresti per primo entrando in quella stanza?'],
      ['Where does the phone move next, and for how long?', 'Dove va il telefono dopo, e per quanti secondi?'],
      ['How many seconds does your last shot have left?', 'Quanti secondi restano alla tua ultima inquadratura?']),
    h(['0s “What was your worst awkward moment?” Tino: “Giant banana. Birthday party. 32 degrees.” 7s “Then what happened?” Tino: “A kid asked if I was a lemon.” 14s “And how did it end?” Tino: “I took the head off. Everyone clapped. I kept the costume.” Questions at 0, 7 and 14, so the clip runs 7 + 7 + 6 = 20 seconds.', '0s “Qual è la tua figuraccia peggiore?” Tino: “Banana gigante. Festa di compleanno. 32 gradi.” 7s “E poi cos’è successo?” Tino: “Un bambino mi ha chiesto se ero un limone.” 14s “E com’è finita?” Tino: “Ho tolto la testa. Tutti hanno applaudito. Il costume l’ho tenuto.” Le domande cadono a 0, 7 e 14: la clip dura 7 + 7 + 6 = 20 secondi.'],
      ['Which moment of that story would make people laugh or wince?', 'Quale momento di quella storia farebbe ridere o storcere il naso?'],
      ['Which question gets your friend to tell exactly that moment?', 'Quale domanda fa raccontare proprio quel momento?'],
      ['Does each answer fit in about 5 seconds?', 'Ogni risposta sta in circa 5 secondi?']),
    h(['0-1.5 Hi, welcome back. 1.5-4 Today: flat tyre. 4-6 Ten minutes, one patch. 6-8 Only €5. 8-10 The culprit? 10-12 One tiny nail. Six captions, 12 seconds, none over 5 words, none under 1.5 seconds.', '0-1,5 Ciao, bentornati. 1,5-4 Oggi: gomma a terra. 4-6 Dieci minuti, una toppa. 6-8 Solo 5 €. 8-10 Il colpevole? 10-12 Un chiodino. Sei sottotitoli, 12 secondi, nessuno oltre 5 parole, nessuno sotto 1,5 secondi.'],
      ['Where does Greta pause for breath?', 'Dove prende fiato Greta?'],
      ['Which words can you cut and keep the meaning?', 'Quali parole puoi togliere senza perdere il senso?'],
      ['Do your seconds run from 0 to 12 with no gap?', 'I tuoi secondi vanno da 0 a 12 senza buchi?']),
    h(['0-2s: “Silence. The board. Still.” 2-5s: “One foot. One push. Pure courage.” 5-8s: “It rolls! It rolls!” 8-10s: “Off to buy bread.” 4 + 6 + 4 + 4 = 18 words, under the limit of 20.', '0-2s: “Silenzio. La tavola. Immobile.” 2-5s: “Un piede. Una spinta. Coraggio puro.” 5-8s: “Rotola! Ma rotola davvero!” 8-10s: “A comprare il pane.” 4 + 6 + 4 + 4 = 18 parole, sotto il limite di 20.'],
      ['What is the smallest thing here you could make sound huge?', 'Qual è la cosa più piccola che potresti far sembrare enorme?'],
      ['Which words can you cut to fit the seconds?', 'Quali parole puoi togliere per stare nei secondi?'],
      ['How many words does each line have, and how many are allowed?', 'Quante parole ha ogni riga, e quante ne sono ammesse?']),
    h(['Shot 1 (0-4s): the comment on screen, you smile. Say: “Fair question, Ivo. Let me show you.” Shot 2 (4-9s): a wall clock, then the empty chair. Say: “Every cut gets 30 full minutes.” Shot 3 (9-12s): a hand lays a steaming towel on the chair. Say: “Towel and shave included. Come say hi.” 4 + 5 + 3 = 12 seconds.', 'Inquadratura 1 (0-4s): il commento a schermo, tu sorridi. Dici: “Domanda giusta, Ivo. Ti faccio vedere.” Inquadratura 2 (4-9s): un orologio al muro, poi la poltrona vuota. Dici: “Ogni taglio dura 30 minuti pieni.” Inquadratura 3 (9-12s): una mano posa un asciugamano fumante sulla poltrona. Dici: “Asciugamano e rasatura inclusi. Passa a salutarci.” 4 + 5 + 3 = 12 secondi.'],
      ['What does Ivo really want to know?', 'Cosa vuole davvero sapere Ivo?'],
      ['Which true fact answers it best, without arguing?', 'Quale fatto vero risponde meglio, senza discutere?'],
      ['What does someone see in the first 3 seconds?', 'Cosa vede chi guarda nei primi 3 secondi?']),
  ],
  Selling: [
    h(['Title: Black metal desk lamp, 40 cm tall, bulb included. Text: Works fine. One small chip of paint on the base. €10, pickup in Bologna or I can ship.', 'Titolo: Lampada da scrivania nera in metallo, alta 40 cm, lampadina inclusa. Testo: Funziona bene. Una piccola scheggiatura di vernice sulla base. 10 €, ritiro a Bologna o spedisco.'],
      ['What does a buyer want to know before they message?', 'Cosa vuole sapere chi compra prima di scrivere?'],
      ['Which true facts answer that fastest?', 'Quali fatti veri rispondono più in fretta?'],
      ['How would you mention the chipped paint so it sounds honest, not scary?', 'Come nomini la vernice scheggiata in modo onesto, senza spaventare?']),
    h(['HOOK: “Plain boiled egg. Watch this.” PROOF: [drip the sauce on the egg, take a bite, nod] “Red chilli, garlic, vinegar. Spicy, but no tears.” ASK: “Grab one at a deli: €6.”', 'HOOK: “Uovo sodo, senza niente. Guarda.” PROVA: [goccia di salsa sull’uovo, un morso, annuisco] “Peperoncino rosso, aglio, aceto. Piccante, ma senza lacrime.” RICHIESTA: “Prendila in gastronomia: 6 €.”'],
      ['What makes someone stop scrolling in the first second?', 'Cosa fa fermare qualcuno nel primo secondo?'],
      ['What can the camera show that a sentence can’t?', 'Cosa può mostrare la camera che una frase non può?'],
      ['What is the smallest thing you can ask a viewer to do?', 'Qual è la cosa più piccola che puoi chiedere a chi guarda?']),
    h(['Buyer: “Can you do €30?” Seller: “It has no stains and one new button, so I’d rather not go that low.” Buyer: “€36, and I pick it up at the stall today?” Seller: “€38 and it’s yours. I’ll fold it in a paper bag.”', 'Chi compra: “Mi fai 30 €?” Chi vende: “Non ha macchie e ha un bottone nuovo, quindi preferisco non scendere così tanto.” Chi compra: “36 €, e la ritiro oggi al banco?” Chi vende: “38 € e la giacca è tua. Te la metto in un sacchetto di carta.”'],
      ['Why is the jacket worth €45 to you, in one true sentence?', 'Perché la giacca vale 45 € per te, in una frase vera?'],
      ['Besides the price, what else could you give the buyer?', 'Oltre al prezzo, cos’altro potresti dare a chi compra?'],
      ['What is the lowest price you can still say with a smile?', 'Qual è il prezzo più basso che puoi dire ancora sorridendo?']),
    h(['Hi Sara, I’m from Cera Cera, three of us pour candles by hand in Turin. You said your flat smells of nothing. Can I send you a free Fig Leaf candle? No post needed. If you share it, say it’s a gift.', 'Ciao Sara, sono di Cera Cera: in tre facciamo candele a mano a Torino. Hai detto che casa tua non sa di niente. Ti mando gratis una candela Fig Leaf? Non devi postare nulla; se lo fai, di’ che è un regalo.'],
      ['How would a friend with a tiny shop write to Sara?', 'Come scriverebbe a Sara qualcuno con un piccolo negozio?'],
      ['Which true fact shows you really follow her?', 'Quale fatto vero mostra che la segui davvero?'],
      ['What is the first thing Sara reads, and would she keep reading?', 'Qual è la prima cosa che legge Sara, e continuerebbe a leggere?']),
    h(['Line: Gnomo Prints can’t choose, and the gnome won’t help. You decide. I’ll share the winner tomorrow. Question: Which €8 product would you actually pay for? A: Pack of 6 stickers. B: Set of 4 postcards.', 'Riga: Gnomo Prints non sa scegliere, e lo gnomo non aiuta. Decidi tu. Domani dico quale vince. Domanda: Quale prodotto da 8 € pagheresti davvero? A: Pacchetto da 6 adesivi. B: Set da 4 cartoline.'],
      ['What is the one thing Gnomo Prints needs to find out?', 'Qual è l’unica cosa che Gnomo Prints deve scoprire?'],
      ['How can the question make people think about money, not just taste?', 'Come fa la domanda a far pensare ai soldi, non solo al gusto?'],
      ['What line above the poll makes a friend smile and tap?', 'Quale riga sopra il sondaggio fa sorridere e venire voglia di votare?']),
    h(['Reply: “Hi! Yes, it’s still here. New tuning pegs in March, the strings are old, a scratch on the back. Want to try it Saturday morning?” Silent buyer: “Old strings means buying new ones too, and I wasn’t sure.” Nudge: “Hi again! Quick info: the pegs are new and the strings are old. No worries if it’s not for you.”', 'Risposta: “Ciao! Sì, è ancora qui. Meccaniche nuove a marzo, corde vecchie, un graffio sul retro. Vuoi provarla sabato mattina?” Chi compra tace: “Con le corde vecchie ne servono di nuove, e ho esitato.” Spintarella: “Ciao di nuovo! Info veloce: le meccaniche sono nuove e le corde vecchie. Nessun problema se non fa per te.”'],
      ['What is a person thinking when they send just four words?', 'Cosa pensa una persona quando manda solo tre parole?'],
      ['Which one fact would make you answer, if you were them?', 'Quale fatto ti farebbe rispondere, se fossi al suo posto?'],
      ['What can you say on day two that adds something new, not pressure?', 'Cosa puoi dire il secondo giorno che aggiunge qualcosa, senza pressione?']),
  ],
  Music: [
    h(['Cut: Sad Trombone Tuesday (sorry, not tonight). New order: Pocket Sunrise, Last Bus Home, Tile Floor Groove, Mango Static, Confetti Cannon (Last Bus Home first works too). Why: it starts like waking up and ends like the doorbell.', 'Via: Sad Trombone Tuesday (scusa, non stasera). Nuovo ordine: Pocket Sunrise, Last Bus Home, Tile Floor Groove, Mango Static, Confetti Cannon (va bene anche Last Bus Home per prima). Perché: parte come un risveglio e finisce come il citofono.'],
      ['Which song would make you want to stay home instead?', 'Quale canzone ti farebbe venire voglia di restare a casa?'],
      ['Which songs could open the evening, and which could close it?', 'Quali canzoni potrebbero aprire la serata e quali chiuderla?'],
      ['Two songs are both quiet: which goes first, and why?', 'Due canzoni sono entrambe tranquille: quale va prima, e perché?']),
    h(['Music: tiny, bouncy, claps. It comes in at second 3, as the shutter rolls up. Why: the shutter is the moment Monday actually starts.', 'Musica: piccola, saltellante, battimani. Entra al secondo 3, quando si alza la saracinesca. Perché: la saracinesca è il momento in cui il lunedì parte davvero.'],
      ['How should a Monday feel at second 0, and at second 10?', 'Che effetto deve fare un lunedì al secondo 0, e al secondo 10?'],
      ['Which scene is the happiest moment of the ten seconds?', 'Quale scena è il momento più felice dei dieci secondi?'],
      ['What would be lost if the music started at second 0?', 'Cosa si perderebbe se la musica partisse al secondo 0?']),
    h(['Ouch. A spilled coffee and a bad exam is allowed to ruin a day.\nYou don’t have to be fine tonight.\nI’m coming over with biscuits.\nSong: Slow Kettle, because it sounds like tea made without any questions.', 'Ahi. Un caffè versato e un esame andato male possono rovinare una giornata.\nNon devi stare bene stasera.\nVengo da te con i biscotti.\nCanzone: Slow Kettle, perché suona come un tè preparato senza fare domande.'],
      ['What would you want to hear on a day like that?', 'Cosa vorresti sentirti dire in una giornata così?'],
      ['What is one specific thing from their day you could mention?', 'Quale cosa precisa di quella giornata potresti nominare?'],
      ['Which song would sit with them without saying a word?', 'Quale canzone starebbe accanto a quella persona senza dire una parola?']),
    h(['Name: Rainy Day Pages. Cover: deep green with one open book. Play it while you read the first chapter of something new.', 'Nome: Pagine di Pioggia. Cover: verde scuro con un libro aperto. Mettila mentre leggi il primo capitolo di qualcosa di nuovo.'],
      ['What should a stranger picture in the first second?', 'Cosa deve immaginare una persona qualsiasi nel primo secondo?'],
      ['Which colour and which object belong to this bookshop?', 'Quale colore e quale oggetto appartengono a questa libreria?'],
      ['When, or where, would someone press play on this?', 'Quando, o dove, qualcuno premerebbe play su questa?']),
    h(['Kick: X . . . X . . .\nSnare: . . X . . . X .\nHat: X X X . X X X .\nA heavy thump on 1 and 5, the clap on 3 and 7, and the hat rests on 4 and 8.', 'Cassa: X . . . X . . .\nRullante: . . X . . . X .\nHi-hat: X X X . X X X .\nUn colpo pesante sull’1 e sul 5, il battimani sul 3 e sul 7, e l’hi-hat riposa sul 4 e sull’8.'],
      ['What does a strong, steady gym beat feel like when you tap it?', 'Che effetto ha, battuto, un ritmo forte e costante da palestra?'],
      ['Where do you want the heavy thump, and where the clap?', 'Dove vuoi il colpo pesante, e dove il battimani?'],
      ['Which step could rest so the beat can breathe?', 'Quale passo può restare in pausa perché il ritmo respiri?']),
    h(['One hotplate, one pan, one tiny room\nSmoke alarm sings at half past eight\nBurnt, but the neighbours ask for more\nTiny Pan: dinner’s on the plate', 'Un fornello, una padella, una stanza\nLa cipolla brucia, che serata\nMa i vicini ne vogliono ancora\nTiny Pan, cena apparecchiata'],
      ['What is the one picture you want in a stranger’s head?', 'Quale immagine vuoi mettere in testa a una persona qualsiasi?'],
      ['What goes wrong when you cook in a tiny room?', 'Cosa va storto quando cucini in una stanza minuscola?'],
      ['Which word could end line 2 so line 4 can rhyme with it?', 'Quale parola potrebbe chiudere la riga 2 perché la 4 faccia rima?']),
  ],
  Prompting: [
    h(['Missing: who the post is for, the day, the price, how Dana sounds. Prompt: “Write a short Instagram post for Argilla Studio, a small pottery studio. Saturday class at 10:00, 6 seats, €35 with clay included, you take your bowl home. Readers are students who have never touched clay. Tone: warm and a bit silly, like Dana laughing at her own wobbly bowl. Under 60 words, end with “6 seats, book by DM”.”', 'Manca: per chi è il post, il giorno, il prezzo, come parla Dana. Prompt: “Scrivi un breve post Instagram per Argilla Studio, un piccolo laboratorio di ceramica. Corso il sabato alle 10:00, 6 posti, 35 € con l’argilla inclusa, la ciotola la porti a casa. Chi legge è studente e non ha mai toccato l’argilla. Tono: caldo e un po’ buffo, come Dana che ride della sua ciotola storta. Meno di 60 parole, chiudi con “6 posti, prenota in DM”.”'],
      ['If a stranger read only the prompt, what could they not know?', 'Se uno sconosciuto leggesse solo il prompt, cosa non potrebbe sapere?'],
      ['Which three facts would make someone book?', 'Quali tre fatti farebbero prenotare qualcuno?'],
      ['How would Dana say it out loud to a friend?', 'Come lo direbbe Dana a voce a un’amica o un amico?']),
    h(['“You are a friendly quiz master. Below are my biology notes. Ask me one question at a time, only about these notes, and wait for my answer. If I am right, say so in five words and ask the next one. If I am wrong, give me the right answer in one sentence and ask a similar question later. After 10 questions, tell me my score. Notes: …”', '“Sei un quiz master simpatico. Qui sotto ci sono i miei appunti di biologia. Fammi una domanda alla volta, solo su questi appunti, e aspetta la mia risposta. Se ho ragione dillo in cinque parole e fai la successiva. Se sbaglio dammi la risposta giusta in una frase e fammi più avanti una domanda simile. Dopo 10 domande dimmi il mio punteggio. Appunti: …”'],
      ['Should the AI summarise the notes, or test you on them?', 'L’AI deve riassumere gli appunti o metterti alla prova?'],
      ['What goes wrong if it asks ten questions at once?', 'Cosa va storto se fa dieci domande in una volta?'],
      ['What would help you most right after a wrong answer?', 'Cosa ti aiuterebbe di più subito dopo una risposta sbagliata?']),
    h(['“Plan a surprise dinner for Giulia, who turns 25 on Saturday. 8 friends, a flat with a small kitchen, €60 in total, everyone arrives at 8pm. Giulia is vegetarian, loves lemon and hates loud surprises. Give me a menu with prices and a timeline from 6pm to 11pm, as a list.”', '“Pianifica una cena a sorpresa per Giulia, che compie 25 anni sabato. 8 amici, una casa con la cucina piccola, 60 € in tutto, arrivano tutti alle 20. Giulia è vegetariana, ama il limone e odia le sorprese rumorose. Dammi un menu con i prezzi e una scaletta dalle 18 alle 23, in elenco.”'],
      ['What would a stranger need to know to plan this?', 'Cosa dovrebbe sapere uno sconosciuto per pianificare tutto questo?'],
      ['Which fact changes the menu the most?', 'Quale fatto cambia di più il menu?'],
      ['Where would a stranger have to guess?', 'Dove uno sconosciuto dovrebbe tirare a indovinare?']),
    h(['“When does Trattoria Nonno Pio close on Sundays? If you do not have reliable information about this place, say “I don’t know” instead of guessing. Split your answer into: what you are sure of, what you are guessing, and what I should check. I will call the trattoria before I go.”', '“A che ora chiude la Trattoria Nonno Pio la domenica? Se non hai informazioni affidabili su questo posto, di’ “non lo so” invece di tirare a indovinare. Dividi la risposta in: di cosa sei sicura, cosa stai supponendo e cosa devo controllare. Telefono alla trattoria prima di andare.”'],
      ['What did the AI say that it could not possibly know?', 'Cosa ha detto l’AI che non poteva proprio sapere?'],
      ['Which words would give the AI permission to be unsure?', 'Quali parole darebbero all’AI il permesso di non essere sicura?'],
      ['Who could give Marco the real answer in one minute?', 'Chi potrebbe dare a Marco la risposta vera in un minuto?']),
    h(['“Four flatmates split three costs equally. Marco paid €36 for internet, Chiara €12 for toilet paper and soap, Sara €84 for electricity, Teo paid nothing. Make a table with the columns: name, paid, share, balance (positive if they are owed money). Then show the total and the share per person so I can check.”', '“Quattro coinquilini dividono tre spese in parti uguali. Marco ha pagato 36 € di internet, Chiara 12 € di carta igienica e sapone, Sara 84 € di luce, Teo non ha pagato niente. Fai una tabella con le colonne: nome, pagato, quota, saldo (positivo se deve ricevere soldi). Poi mostra il totale e la quota a testa così posso controllare.”'],
      ['What does the AI need so it does not have to guess the numbers?', 'Cosa serve all’AI perché non debba indovinare i numeri?'],
      ['Which columns would you read first in a table?', 'Quali colonne leggeresti per prime in una tabella?'],
      ['What would you check to know the total is right?', 'Cosa controlleresti per capire se il totale è giusto?']),
    h(['“Someone I know cares about two things: a short walk to the station and a quiet street. Compare Flat A (€520, 25 min, quiet street, no balcony) and Flat B (€580, 8 min, busy street, small balcony) on those two things only. Pick one, then tell me one reason the pick might be wrong for them.”', '“Una persona che conosco tiene a due cose: poca strada fino alla stazione e una via tranquilla. Confronta la Casa A (520 €, 25 min, via tranquilla, senza balcone) e la Casa B (580 €, 8 min, via trafficata, piccolo balcone) solo su queste due cose. Scegline una, poi dimmi un motivo per cui la scelta potrebbe essere sbagliata per quella persona.”'],
      ['What does the other person look at first when they visit a flat?', 'Cosa guarda per prima cosa l’altra persona quando visita una casa?'],
      ['Which facts about the flats touch those two things?', 'Quali dati delle case riguardano quelle due cose?'],
      ['What would make you doubt the pick?', 'Cosa ti farebbe dubitare della scelta?']),
  ],
};
