import { t2 } from './i18n';

// Per mission (same field and index as missions.ts): one worked example of a strong answer, and three hints that go
// from broad to specific. Hints are always questions: KERN.AI asks, it never answers for you.
export type Help = { ex: string; hints: string[] };
const h = (ex: [string, string], a: [string, string], b: [string, string], c: [string, string]): Help => ({
  ex: t2(...ex), hints: [t2(...a), t2(...b), t2(...c)],
});

export const HELPS: Record<string, Help[]> = {
  Design: [
    h(['Cut: phone, birthday, city, invite. New flow: 1) Email only, button “Start my first habit”. 2) Pick one habit from 3 suggestions. 3) Set one reminder. First win: tick the habit today.', 'Taglio: telefono, nascita, città, inviti. Nuovo flusso: 1) Solo email, pulsante “Inizia la mia prima abitudine”. 2) Scegli una abitudine tra 3 suggerite. 3) Imposta un promemoria. Prima vittoria: spunta l’abitudine oggi.'],
      ['How many things do you really need to ask before someone gets value?', 'Quante cose ti servono davvero prima che qualcuno ottenga valore?'],
      ['Which screen could wait until after the first habit?', 'Quale schermata può aspettare dopo la prima abitudine?'],
      ['What could the button say instead of “Continue”?', 'Cosa potrebbe dire il pulsante invece di “Continua”?']),
    h(['Step 1 (4 fields): name, email, class, date. Button: “Save my spot”. Step 2, after booking: phone, experience, health notes. Label: “Anything we should know? (optional)”.', 'Passo 1 (4 campi): nome, email, lezione, data. Pulsante: “Salva il mio posto”. Passo 2, dopo la prenotazione: telefono, esperienza, note di salute. Etichetta: “Qualcosa da sapere? (facoltativo)”.'],
      ['What does the studio need to hold a spot?', 'Cosa serve allo studio per tenere un posto?'],
      ['What would you ask a friend first?', 'Cosa chiederesti prima a un amico?'],
      ['Which questions feel personal and can wait?', 'Quali domande sembrano personali e possono aspettare?']),
    h(['Top: a grey sample expense “Coffee · €2.50”. Headline: “Log your first coffee”. Button: “Add it in 5 seconds”. After the tap the sample turns real and the screen says “Today: €2.50”.', 'In alto: una spesa di esempio grigia “Caffè · 2,50 €”. Titolo: “Registra il tuo primo caffè”. Pulsante: “Aggiungilo in 5 secondi”. Dopo il tocco l’esempio diventa vero e lo schermo dice “Oggi: 2,50 €”.'],
      ['What would make an empty screen feel alive?', 'Cosa renderebbe viva una schermata vuota?'],
      ['What is the one action you want first?', 'Qual è l’unica azione che vuoi per prima?'],
      ['What do they see right after tapping?', 'Cosa vedono subito dopo il tocco?']),
  ],
  Writing: [
    h(['Headline: “Why prices rise just because we expect them to”. Text: If everyone thinks prices will go up, workers ask for more pay and shops raise prices to afford it. The fear makes the rise happen. Banks work to calm that fear.', 'Titolo: “Perché i prezzi salgono solo perché ce lo aspettiamo”. Testo: Se tutti pensano che i prezzi saliranno, i lavoratori chiedono più paga e i negozi alzano i prezzi per pagarla. La paura fa avverare l’aumento. Le banche lavorano per calmare quella paura.'],
      ['Say the idea out loud to a friend in one sentence.', 'Di’ l’idea a voce a un amico in una frase.'],
      ['What everyday example shows it: a bus ticket, a pizza?', 'Quale esempio quotidiano la mostra: un biglietto dell’autobus, una pizza?'],
      ['Which words would a 15-year-old skip?', 'Quali parole un quindicenne salterebbe?']),
    h(['Subject: Send September expenses by Fri 28. Hi all, please send your September expenses by Friday 28. A new process is coming, details later. Questions? Reply here. Thanks!', 'Oggetto: Invia le spese di settembre entro ven 28. Ciao a tutti, inviate le spese di settembre entro venerdì 28. Arriva un nuovo processo, dettagli più avanti. Domande? Rispondete qui. Grazie!'],
      ['What is the one thing people must do?', 'Qual è l’unica cosa che le persone devono fare?'],
      ['By when, exactly?', 'Entro quando, esattamente?'],
      ['Which sentence could you delete without losing the task?', 'Quale frase potresti cancellare senza perdere il compito?']),
    h(['2) Nobody had told the machine it could. 3) It printed a ticket that said “Ask me again tomorrow.” 4) Mara asked the next day anyway. 5) Then it asked her name.', '2) Nessuno aveva detto alla macchina che poteva. 3) Stampò un biglietto: “Chiedimelo ancora domani.” 4) Mara glielo chiese il giorno dopo. 5) Poi chiese il suo nome.'],
      ['What strange but specific detail could come next?', 'Quale dettaglio strano ma preciso potrebbe venire dopo?'],
      ['What would a person standing there notice?', 'Cosa noterebbe una persona lì in piedi?'],
      ['How could the last sentence close the circle?', 'Come potrebbe l’ultima frase chiudere il cerchio?']),
  ],
  Code: [
    h(['Two bugs. The id in JS is copyBtn but the HTML says copy-btn. And addEventListener(\'click\', copyLink()) calls the function immediately; it should be copyLink without the brackets. Fix both and the click works.', 'Due errori. L’id nel JS è copyBtn ma l’HTML dice copy-btn. E addEventListener(\'click\', copyLink()) chiama subito la funzione; deve essere copyLink senza parentesi. Correggi entrambi e il click funziona.'],
      ['Is the id in the HTML the same as in the JavaScript?', 'L’id nell’HTML è uguale a quello nel JavaScript?'],
      ['What is the difference between copyLink and copyLink()?', 'Che differenza c’è tra copyLink e copyLink()?'],
      ['What happens at the moment the page loads?', 'Cosa succede nel momento in cui la pagina si carica?']),
    h(['function split(total, people, tip) {\n  if (people < 1) return null; // nobody to pay\n  return +(total * (1 + tip / 100) / people).toFixed(2);\n}\nsplit(80, 4, 10) gives 22.', 'function split(totale, persone, mancia) {\n  if (persone < 1) return null; // nessuno da far pagare\n  return +(totale * (1 + mancia / 100) / persone).toFixed(2);\n}\nsplit(80, 4, 10) dà 22.'],
      ['What do you do to the total before dividing?', 'Cosa fai al totale prima di dividere?'],
      ['How do you round to cents?', 'Come arrotondi ai centesimi?'],
      ['What should happen with 0 people?', 'Cosa dovrebbe succedere con 0 persone?']),
    h(['CSS: :root{--bg:#fff;--fg:#111} [data-theme=dark]{--bg:#111;--fg:#eee}. JS: on click, flip document.documentElement.dataset.theme and save it in localStorage. On load: use the saved value, or matchMedia(\'(prefers-color-scheme: dark)\') if there is none.', 'CSS: :root{--bg:#fff;--fg:#111} [data-theme=dark]{--bg:#111;--fg:#eee}. JS: al click, inverti document.documentElement.dataset.theme e salvalo in localStorage. Al caricamento: usa il valore salvato, o matchMedia(\'(prefers-color-scheme: dark)\') se non c’è.'],
      ['Which colours need to change? Put them in variables.', 'Quali colori devono cambiare? Mettili in variabili.'],
      ['Where can a page remember a choice?', 'Dove può una pagina ricordare una scelta?'],
      ['What if the user never chose?', 'E se l’utente non ha mai scelto?']),
  ],
  Video: [
    h(['Order: 07 croissant tearing (5s, the hook), 03 flour cloud (3s), 11 oven glow (7s), 10 kid pointing (4s) = 19s. It opens on steam, not on the sign. Caption: “Fresh from the oven, still warm.”', 'Ordine: 07 cornetto che si apre (5s, l’aggancio), 03 nuvola di farina (3s), 11 bagliore del forno (7s), 10 bimbo che indica (4s) = 19s. Apre sul vapore, non sul cartello. Didascalia: “Appena sfornato, ancora caldo.”'],
      ['What is the most surprising or beautiful moment?', 'Qual è il momento più sorprendente o bello?'],
      ['Which clips show action, not a shop standing still?', 'Quali clip mostrano azione, non un negozio fermo?'],
      ['Do your durations add up to under 20 seconds?', 'Le durate fanno meno di 20 secondi in totale?']),
    h(['Topic: why pasta water should be salty. Hook: “You’re ruining your pasta without knowing it.” Claim: salt goes in the water, not on the plate. Show: tasting two bites side by side. Close: “Salt the water. Always.”', 'Argomento: perché l’acqua della pasta va salata. Aggancio: “Stai rovinando la pasta senza saperlo.” Tesi: il sale va nell’acqua, non nel piatto. Mostra: assaggio di due bocconi a confronto. Chiusa: “Sala l’acqua. Sempre.”'],
      ['What do you know that most people get wrong?', 'Cosa sai che la maggior parte della gente sbaglia?'],
      ['What is the one thing to remember?', 'Qual è l’unica cosa da ricordare?'],
      ['What does the viewer see on each line?', 'Cosa vede lo spettatore a ogni riga?']),
    h(['Order: A bottle on the desk → B hand twists the cap → C water pours → E drop test (the hero). Sound: quiet, then one loud thud on the drop. Tagline: “Built to be dropped.”', 'Ordine: A borraccia sulla scrivania → B mano che gira il tappo → C acqua che scorre → E prova di caduta (la protagonista). Suono: silenzio, poi un tonfo forte sulla caduta. Slogan: “Fatta per cadere.”'],
      ['Which shot proves the bottle is special?', 'Quale inquadratura prova che la borraccia è speciale?'],
      ['Need, use, proof: which shot fits each?', 'Bisogno, uso, prova: quale inquadratura per ciascuno?'],
      ['Where would silence make something louder?', 'Dove il silenzio renderebbe qualcosa più forte?']),
  ],
  Selling: [
    h(['Marta, your coworking has coffee but nothing sweet. Our €12 box has 8 fresh pastries, delivered at 9. The café next door sells coffee; we bring what it doesn’t. Can I drop one off on Friday to try?', 'Marta, nel tuo coworking c’è il caffè ma niente di dolce. La nostra box da 12 € ha 8 pasticcini freschi, consegnata alle 9. Il bar accanto vende caffè; noi portiamo ciò che non ha. Posso lasciartene una venerdì da provare?'],
      ['What does Marta lack right now?', 'Cosa manca a Marta in questo momento?'],
      ['What would she answer to “we already have a café”?', 'Cosa risponderesti a “abbiamo già un bar”?'],
      ['What small question is easy to say yes to?', 'Quale piccola domanda è facile a cui dire di sì?']),
    h(['Subject: Your Lisbon rebrand. Dana, I loved how the Lisbon rebrand used just one colour. Quick yes/no question about how you price projects: ok if I send it? Just reply “yes”.', 'Oggetto: Il tuo rebrand di Lisbona. Dana, mi è piaciuto come il rebrand di Lisbona usa un solo colore. Una domanda sì/no su come prezzi i progetti: posso mandartela? Rispondi solo “sì”.'],
      ['What did all three ignored messages have in common?', 'Cosa avevano in comune i tre messaggi ignorati?'],
      ['What detail proves you looked at her work?', 'Quale dettaglio prova che hai guardato il suo lavoro?'],
      ['What is the tiniest thing you can ask?', 'Qual è la cosa più piccola che puoi chiedere?']),
    h(['1) “What would great sound feel like to you?” Then the price makes sense. 2) “What do yours not do on a loud train?” 3) “Totally fair. Can you test mine on tomorrow’s commute at 9?”', '1) “Che sensazione ti darebbe un suono ottimo?” Poi il prezzo ha senso. 2) “Cosa non fanno le tue su un treno rumoroso?” 3) “Giusto. Le provi sul tragitto di domani alle 9?”'],
      ['Which question makes them describe what they need?', 'Quale domanda li fa descrivere ciò che serve?'],
      ['What does their current pair fail at?', 'In cosa sbagliano le loro cuffie attuali?'],
      ['What time and place can you propose?', 'Che orario e luogo puoi proporre?']),
  ],
  Music: [
    h(['Instrument: soft piano, slow (60 bpm). Notes: C – E – G – C. It starts with one quiet C and ends on a held low C, like a deep breath.', 'Strumento: pianoforte morbido, lento (60 bpm). Note: DO – MI – SOL – DO. Parte con un DO piano e finisce su un DO grave tenuto, come un respiro profondo.'],
      ['Which instrument sounds warm and slow to you?', 'Quale strumento ti suona caldo e lento?'],
      ['How many notes fit in 6 seconds at a slow pace?', 'Quante note stanno in 6 secondi a ritmo lento?'],
      ['Which note feels like an ending?', 'Quale nota sembra una fine?']),
    h(['Song: “Let It Be”. Feeling: calm. Keep: the chorus melody. Change: slow it to 60 bpm and play it on one guitar. Add: soft rain. Drop: the drums. Result: a sleepy rainy-day version.', 'Canzone: “Let It Be”. Sensazione: calma. Tieni: la melodia del ritornello. Cambia: rallenta a 60 bpm e suona con una chitarra sola. Aggiungi: pioggia leggera. Togli: la batteria. Risultato: una versione assonnata da giorno di pioggia.'],
      ['What feeling should the remix give?', 'Che sensazione deve dare il remix?'],
      ['Which one part must stay so people recognise it?', 'Quale parte deve restare perché la riconoscano?'],
      ['What would you remove to make space?', 'Cosa toglieresti per fare spazio?']),
    h(['Melody over C–G: E E G G, then up to A. Words: “Go on, move, move!” Loudest beat on the first “move”.', 'Melodia su DO–SOL: MI MI SOL SOL, poi sale al LA. Parole: “Dai, muoviti, muoviti!” Battito più forte sul primo “muoviti”.'],
      ['What short pattern can repeat on C and G?', 'Quale breve schema può ripetersi su DO e SOL?'],
      ['Which word sells the shoe?', 'Quale parola vende la scarpa?'],
      ['Where is the strongest beat in the loop?', 'Dov’è il battito più forte nel giro?']),
  ],
};
