import { t2 } from './i18n';

// Per mission (same field and index as missions.ts): one worked example of a strong answer, and three hints that go
// from broad to specific. Hints are always questions: KERN.AI asks, it never answers for you.
export type Help = { ex: string; hints: string[] };
const h = (ex: [string, string], a: [string, string], b: [string, string], c: [string, string]): Help => ({
  ex: t2(...ex), hints: [t2(...a), t2(...b), t2(...c)],
});

export const HELPS: Record<string, Help[]> = {
  Design: [
    h(['Cut: phone, birthday, city, invite. New flow: 1) Email only, button “Start my first habit”. 2) Pick one habit from 3 suggestions. 3) Set one reminder. First win: tick the habit today.', 'Taglio: telefono, nascita, città, inviti. Nuovo flusso: 1) Solo email, pulsante “Inizia la mia prima abitudine”. 2) Scegli una abitudine tra 3 suggerite. 3) Imposta un promemoria. Prima vittoria: spunta l’abitudine oggi.'],
      ['How many things do you really need to ask before someone gets value?', 'Quante cose ti servono davvero prima che qualcuno ottenga valore?'],
      ['Which screen could wait until after the first habit?', 'Quale schermata può aspettare dopo la prima abitudine?'],
      ['What could the button say instead of “Continue”?', 'Cosa potrebbe dire il pulsante invece di “Continua”?']),
    h(['Step 1 (4 fields): name, email, class, date. Button: “Save my spot”. Step 2, after booking: phone, experience, health notes. Label: “Anything we should know? (optional)”.', 'Passo 1 (4 campi): nome, email, lezione, data. Pulsante: “Salva il mio posto”. Passo 2, dopo la prenotazione: telefono, esperienza, note di salute. Etichetta: “Qualcosa da sapere? (facoltativo)”.'],
      ['What does the studio need to hold a spot?', 'Cosa serve allo studio per tenere un posto?'],
      ['What would you ask a friend first?', 'Cosa chiederesti prima a un amico?'],
      ['Which questions feel personal and can wait?', 'Quali domande sembrano personali e possono aspettare?']),
    h(['Top: a grey sample expense “Coffee · €2.50”. Headline: “Log your first coffee”. Button: “Add it in 5 seconds”. After the tap the sample turns real and the screen says “Today: €2.50”.', 'In alto: una spesa di esempio grigia “Caffè · 2,50 €”. Titolo: “Registra il tuo primo caffè”. Pulsante: “Aggiungilo in 5 secondi”. Dopo il tocco l’esempio diventa vero e lo schermo dice “Oggi: 2,50 €”.'],
      ['What would make an empty screen feel alive?', 'Cosa renderebbe viva una schermata vuota?'],
      ['What is the one action you want first?', 'Qual è l’unica azione che vuoi per prima?'],
      ['What do they see right after tapping?', 'Cosa vedono subito dopo il tocco?']),
    h(['Title: “No signal, map still works”. Sentence: Weather and trail reports will update when your signal is back. Still working: saved maps and your track. Button: “Back to my map”.', 'Titolo: “Niente segnale, la mappa funziona”. Frase: Meteo e segnalazioni si aggiorneranno quando torna il segnale. Funzionano ancora: mappe salvate e percorso. Pulsante: “Torna alla mia mappa”.'],
      ['What does a tired hiker need to know in the first second?', 'Cosa deve sapere un escursionista stanco nel primo secondo?'],
      ['Which words in the old message blame the hiker or sound scary?', 'Quali parole del vecchio messaggio danno la colpa all’escursionista o fanno paura?'],
      ['Which true fact on the list would calm you most, and where does it go?', 'Quale fatto vero dell’elenco ti calmerebbe di più, e dove lo metti?']),
    h(['Hero: “V5” huge, in the centre, because it is a first. Small facts: “52 sent” and “14 sessions”. Bottom: a tiny “Topout”. Colours: chalk white on deep blue. Line: “Gravity lost this month.”', 'Protagonista: “V5” enorme, al centro, perché è la prima volta. Dati piccoli: “52 vie” e “14 sessioni”. In basso: un “Topout” piccolo. Colori: bianco gesso su blu profondo. Riga: “Questo mese la gravità ha perso.”'],
      ['Which one number would a climber be proud to show a friend?', 'Quale numero un arrampicatore sarebbe fiero di mostrare a un amico?'],
      ['What does the card look like at thumbnail size, and what disappears?', 'Com’è la card grande quanto una miniatura, e cosa sparisce?'],
      ['What could the line say that no number can?', 'Cosa potrebbe dire la riga che nessun numero può dire?']),
    h(['Order: A summary with a live total, B address, C shipping (Standard preselected), E payment, G button. D hides behind “Have a code?” and F behind “Add a gift note”. H sits under the button. Button: “Pay €43.30”. Shipping line: “Standard €4.90, change it any time”. Reassurance: “Free returns for 30 days”.', 'Ordine: A riepilogo con totale aggiornato, B indirizzo, C spedizione (Standard già scelta), E pagamento, G pulsante. D si nasconde dietro “Hai un codice?” e F dietro “Aggiungi un biglietto”. H sta sotto il pulsante. Pulsante: “Paga 43,30 €”. Riga spedizione: “Standard 4,90 €, puoi cambiarla quando vuoi”. Rassicurazione: “Resi gratis per 30 giorni”.'],
      ['What question is a shopper silently asking at the shipping step?', 'Quale domanda si fa in silenzio chi compra al passo della spedizione?'],
      ['Which blocks does almost everyone use, and which only a few?', 'Quali blocchi usano quasi tutti, e quali solo pochi?'],
      ['What amount should the button show so the total never jumps at the end?', 'Quale importo deve mostrare il pulsante perché il totale non salga all’ultimo?']),
  ],
  Writing: [
    h(['Headline: “Why prices rise just because we expect them to”. Text: If everyone thinks prices will go up, workers ask for more pay and shops raise prices to afford it. The fear makes the rise happen. Banks work to calm that fear.', 'Titolo: “Perché i prezzi salgono solo perché ce lo aspettiamo”. Testo: Se tutti pensano che i prezzi saliranno, i lavoratori chiedono più paga e i negozi alzano i prezzi per pagarla. La paura fa avverare l’aumento. Le banche lavorano per calmare quella paura.'],
      ['Say the idea out loud to a friend in one sentence.', 'Di’ l’idea a voce a un amico in una frase.'],
      ['What everyday example shows it: a bus ticket, a pizza?', 'Quale esempio quotidiano la mostra: un biglietto dell’autobus, una pizza?'],
      ['Which words would a 15-year-old skip?', 'Quali parole un quindicenne salterebbe?']),
    h(['Subject: Send September expenses by Fri 28. Hi all, please send your September expenses by Friday 28. A new process is coming, details later. Questions? Reply here. Thanks!', 'Oggetto: Invia le spese di settembre entro ven 28. Ciao a tutti, inviate le spese di settembre entro venerdì 28. Arriva un nuovo processo, dettagli più avanti. Domande? Rispondete qui. Grazie!'],
      ['What is the one thing people must do?', 'Qual è l’unica cosa che le persone devono fare?'],
      ['By when, exactly?', 'Entro quando, esattamente?'],
      ['Which sentence could you delete without losing the task?', 'Quale frase potresti cancellare senza perdere il compito?']),
    h(['2) Nobody had told the machine it could. 3) It printed a ticket that said “Ask me again tomorrow.” 4) Mara asked the next day anyway. 5) Then it asked her name.', '2) Nessuno aveva detto alla macchina che poteva. 3) Stampò un biglietto: “Chiedimelo ancora domani.” 4) Mara glielo chiese il giorno dopo. 5) Poi chiese il suo nome.'],
      ['What strange but specific detail could come next?', 'Quale dettaglio strano ma preciso potrebbe venire dopo?'],
      ['What would a person standing there notice?', 'Cosa noterebbe una persona lì in piedi?'],
      ['How could the last sentence close the circle?', 'Come potrebbe l’ultima frase chiudere il cerchio?']),
    h(['Headline: “Cedar smoke for slow evenings”. Text: Three weeks of evenings in one jar. It smells of cedar, a little smoke, dry vanilla. Light it when the laptop closes, and the room slows down. Button: “Light up my evening · €24”.', 'Titolo: “Fumo di cedro per sere lente”. Testo: Tre settimane di sere in un vasetto. Profuma di cedro, un po’ di fumo, vaniglia secca. Accendila quando chiudi il computer e la stanza rallenta. Pulsante: “Accendi la mia sera · 24 €”.'],
      ['What would you say if a friend asked why you like this candle?', 'Cosa diresti se un amico ti chiedesse perché ti piace questa candela?'],
      ['Which sentence tells you nothing you could not say about any candle?', 'Quale frase non ti dice nulla che non potresti dire di qualsiasi candela?'],
      ['What can you swap “the ultimate in relaxation” for: a smell, a moment, a number?', 'Con cosa puoi sostituire “il massimo del relax”: un profumo, un momento, un numero?']),
    h(['Forty hives sit on rooftops across this city. Their keeper started at 19, when a swarm landed on her balcony and stayed all night. Now she teaches kids about bees, free, every Saturday. Please welcome Ines Varga.', 'Quaranta arnie sui tetti di questa città. A 19 anni, la loro custode ha visto uno sciame posarsi sul suo balcone e restarci tutta la notte. Ogni sabato insegna ai bambini, gratis. Un applauso per Ines Varga.'],
      ['If you had 15 seconds to make a stranger curious about her, what would you say?', 'Se avessi 15 secondi per incuriosire uno sconosciuto su di lei, cosa diresti?'],
      ['Which of the nine facts can you picture, and which only sound impressive?', 'Quali dei nove fatti riesci a immaginare, e quali suonano solo impressionanti?'],
      ['Which sentence ends with her name, so the room knows when to clap?', 'Quale frase finisce con il suo nome, così la sala sa quando applaudire?']),
    h(['Customer: Hi, the fern I bought as a gift arrived with brown leaves and a cracked pot. I need a healthy one by Saturday. Can you do that? Support: I’m sorry, a gift should not arrive like this. Can you send a photo? A new fern ships today and lands Friday. Customer: Friday works. Can the pot be a sturdy one? Support: Done, sturdy pot added free. Send the photo and it ships today. Enjoy the party!', 'Cliente: Ciao, la felce che ho comprato come regalo è arrivata con le foglie marroni e il vaso rotto. Me ne serve una sana entro sabato. Si può fare? Assistenza: Mi dispiace, un regalo non dovrebbe arrivare così. Puoi mandarmi una foto? Una felce nuova parte oggi e arriva venerdì. Cliente: Venerdì va bene. Il vaso può essere uno robusto? Assistenza: Fatto, vaso robusto in omaggio. Mandami la foto e parte oggi. Buona festa!'],
      ['What does each of them actually want, in one sentence?', 'Cosa vuole davvero ciascuno dei due, in una frase?'],
      ['What is the first thing the customer needs to hear from support?', 'Qual è la prima cosa che chi ha comprato deve sentirsi dire dall’assistenza?'],
      ['Which small extra could close the deal without breaking support’s rules?', 'Quale piccolo extra potrebbe chiudere l’accordo senza infrangere le regole dell’assistenza?']),
  ],
  Code: [
    h(['Two bugs. The id in JS is copyBtn but the HTML says copy-btn. And addEventListener(\'click\', copyLink()) calls the function immediately; it should be copyLink without the brackets. Fix both and the click works.', 'Due errori. L’id nel JS è copyBtn ma l’HTML dice copy-btn. E addEventListener(\'click\', copyLink()) chiama subito la funzione; deve essere copyLink senza parentesi. Correggi entrambi e il click funziona.'],
      ['Is the id in the HTML the same as in the JavaScript?', 'L’id nell’HTML è uguale a quello nel JavaScript?'],
      ['What is the difference between copyLink and copyLink()?', 'Che differenza c’è tra copyLink e copyLink()?'],
      ['What happens at the moment the page loads?', 'Cosa succede nel momento in cui la pagina si carica?']),
    h(['function split(total, people, tip) {\n  if (people < 1) return null; // nobody to pay\n  return +(total * (1 + tip / 100) / people).toFixed(2);\n}\nsplit(80, 4, 10) gives 22.', 'function split(totale, persone, mancia) {\n  if (persone < 1) return null; // nessuno da far pagare\n  return +(totale * (1 + mancia / 100) / persone).toFixed(2);\n}\nsplit(80, 4, 10) dà 22.'],
      ['What do you do to the total before dividing?', 'Cosa fai al totale prima di dividere?'],
      ['How do you round to cents?', 'Come arrotondi ai centesimi?'],
      ['What should happen with 0 people?', 'Cosa dovrebbe succedere con 0 persone?']),
    h(['CSS: :root{--bg:#fff;--fg:#111} [data-theme=dark]{--bg:#111;--fg:#eee}. JS: on click, flip document.documentElement.dataset.theme and save it in localStorage. On load: use the saved value, or matchMedia(\'(prefers-color-scheme: dark)\') if there is none.', 'CSS: :root{--bg:#fff;--fg:#111} [data-theme=dark]{--bg:#111;--fg:#eee}. JS: al click, inverti document.documentElement.dataset.theme e salvalo in localStorage. Al caricamento: usa il valore salvato, o matchMedia(\'(prefers-color-scheme: dark)\') se non c’è.'],
      ['Which colours need to change? Put them in variables.', 'Quali colori devono cambiare? Mettili in variabili.'],
      ['Where can a page remember a choice?', 'Dove può una pagina ricordare una scelta?'],
      ['What if the user never chose?', 'E se l’utente non ha mai scelto?']),
    h(['Trace: pageCount(23, 10) gives 2, pageCount(20, 10) gives 2 (passes), firstOnPage(1, 10) gives 10, firstOnPage(3, 10) gives 30. Fix: Math.ceil in pageCount (a “+ 1” would break the 20 case) and (page - 1) * perPage in firstOnPage. New check: pageCount(21, 10) want 3, one book spills onto a new page.', 'Traccia: pageCount(23, 10) dà 2, pageCount(20, 10) dà 2 (passa), firstOnPage(1, 10) dà 10, firstOnPage(3, 10) dà 30. Correzione: Math.ceil in pageCount (un “+ 1” romperebbe il caso del 20) e (page - 1) * perPage in firstOnPage. Nuovo controllo: pageCount(21, 10) atteso 3, un libro sfora su una pagina nuova.'],
      ['Which of the 4 checks does the code already pass, and why?', 'Quale dei 4 controlli il codice supera già, e perché?'],
      ['What does Math.floor do to 2.3, and what do you want for 23 books?', 'Cosa fa Math.floor a 2.3, e cosa vuoi per 23 libri?'],
      ['How many full pages come before page 3, and how many books are on them?', 'Quante pagine piene vengono prima della pagina 3, e quanti libri contengono?']),
    h(['function currentStreak(days) {\n  let count = 0;\n  for (let i = days.length - 1; i >= 0; i--) {\n    if (!days[i]) break;\n    count++;\n  }\n  return count;\n}\nExamples: [false, true, true] -> 2 · [true, true, false] -> 0 (today is false) · [] -> 0.', 'function currentStreak(days) {\n  let count = 0;\n  for (let i = days.length - 1; i >= 0; i--) {\n    if (!days[i]) break;\n    count++;\n  }\n  return count;\n}\nEsempi: [false, true, true] -> 2 · [true, true, false] -> 0 (oggi è false) · [] -> 0.'],
      ['Which end of the list does the streak start from?', 'Da quale estremità della lista parte la serie?'],
      ['What should the loop do the moment it meets a false?', 'Cosa deve fare il ciclo nel momento in cui incontra un false?'],
      ['Which tricky input would fool a lazy version: a false at the end, or an empty list?', 'Quale input insidioso ingannerebbe una versione pigra: un false alla fine, o la lista vuota?']),
    h(['Tests (partner A): countWords("") -> 0 · countWords("   ") -> 0 · countWords("hello world") -> 2 · countWords("  well-known   idea ") -> 2. Function (partner B): function countWords(text) {\n  const t = text.trim();\n  return t ? t.split(/\\s+/).length : 0;\n}\nTrace all four by hand: they pass.', 'Test (partner A): countWords("") -> 0 · countWords("   ") -> 0 · countWords("hello world") -> 2 · countWords("  well-known   idea ") -> 2. Funzione (partner B): function countWords(text) {\n  const t = text.trim();\n  return t ? t.split(/\\s+/).length : 0;\n}\nSegui tutti e quattro a mano: passano.'],
      ['What odd things could someone type into a text box?', 'Che cose strane potrebbe scrivere qualcuno in una casella di testo?'],
      ['What happens to two spaces in a row if you split on single spaces?', 'Cosa succede a due spazi di fila se dividi sugli spazi singoli?'],
      ['What should an empty text give back, and which of your tests proves it?', 'Cosa deve restituire un testo vuoto, e quale dei tuoi test lo prova?']),
  ],
  Video: [
    h(['Order: 07 croissant tearing (5s, the hook), 03 flour cloud (3s), 11 oven glow (7s), 10 kid pointing (4s) = 19s. It opens on steam, not on the sign. Caption: “Fresh from the oven, still warm.”', 'Ordine: 07 cornetto che si apre (5s, l’aggancio), 03 nuvola di farina (3s), 11 bagliore del forno (7s), 10 bimbo che indica (4s) = 19s. Apre sul vapore, non sul cartello. Didascalia: “Appena sfornato, ancora caldo.”'],
      ['What is the most surprising or beautiful moment?', 'Qual è il momento più sorprendente o bello?'],
      ['Which clips show action, not a shop standing still?', 'Quali clip mostrano azione, non un negozio fermo?'],
      ['Do your durations add up to under 20 seconds?', 'Le durate fanno meno di 20 secondi in totale?']),
    h(['Topic: why pasta water should be salty. Hook: “You’re ruining your pasta without knowing it.” Claim: salt goes in the water, not on the plate. Show: tasting two bites side by side. Close: “Salt the water. Always.”', 'Argomento: perché l’acqua della pasta va salata. Aggancio: “Stai rovinando la pasta senza saperlo.” Tesi: il sale va nell’acqua, non nel piatto. Mostra: assaggio di due bocconi a confronto. Chiusa: “Sala l’acqua. Sempre.”'],
      ['What do you know that most people get wrong?', 'Cosa sai che la maggior parte della gente sbaglia?'],
      ['What is the one thing to remember?', 'Qual è l’unica cosa da ricordare?'],
      ['What does the viewer see on each line?', 'Cosa vede lo spettatore a ogni riga?']),
    h(['Order: A bottle on the desk → B hand twists the cap → C water pours → E drop test (the hero). Sound: quiet, then one loud thud on the drop. Tagline: “Built to be dropped.”', 'Ordine: A borraccia sulla scrivania → B mano che gira il tappo → C acqua che scorre → E prova di caduta (la protagonista). Suono: silenzio, poi un tonfo forte sulla caduta. Slogan: “Fatta per cadere.”'],
      ['Which shot proves the bottle is special?', 'Quale inquadratura prova che la borraccia è speciale?'],
      ['Need, use, proof: which shot fits each?', 'Bisogno, uso, prova: quale inquadratura per ciascuno?'],
      ['Where would silence make something louder?', 'Dove il silenzio renderebbe qualcosa più forte?']),
    h(['Drop 1 (logo), 2 (talking), 3 and 5 (the bike just standing) and 9 (empty shop): 24s gone. Keep, in order: 4 nail (5s) → 6 bubbles (4s) → 7 inflate (5s) → 8 rider leaves (3s) = 17s. Opens on the nail, ends on the rider. Payoff: the tyre inflates, from second 9.', 'Tolgo 1 (logo), 2 (parlato), 3 e 5 (la bici ferma) e 9 (negozio vuoto): via 24s. Tengo, in ordine: 4 chiodo (5s) → 6 bolle (4s) → 7 gonfiaggio (5s) → 8 il ciclista parte (3s) = 17s. Apre sul chiodo, chiude sul ciclista. Momento clou: la gomma che si gonfia, dal secondo 9.'],
      ['What is the first moment that makes you curious about what happens next?', 'Qual è il primo momento che ti incuriosisce su cosa succede dopo?'],
      ['Which shots show the same thing twice, or nothing happening?', 'Quali inquadrature mostrano due volte la stessa cosa, o niente che succeda?'],
      ['Do your seconds add up to 25 or less, and does the order go from problem to fix?', 'I tuoi secondi fanno 25 o meno, e l’ordine va dal problema alla soluzione?']),
    h(['0-2s: scissors snip basil from the full pot over a pan. Text: “Dead basil? Not this time.” 2-6s: three pots on a railing, a hand waters them. Text: “3 pots. 1 railing.” 6-12s: three quick cuts: empty pot, seedling, full pot. 12-16s: fresh leaves fall into the pan. Text: “Balcony Basil”. 16-18s: “Start with one pot.”', '0-2s: delle forbici tagliano il basilico del vaso pieno sopra una padella. Testo: “Basilico morto? Stavolta no.” 2-6s: tre vasi su una ringhiera, una mano li annaffia. Testo: “3 vasi. 1 ringhiera.” 6-12s: tre stacchi veloci: vaso vuoto, piantina, vaso pieno. 12-16s: foglie fresche cadono nella padella. Testo: “Balcony Basil”. 16-18s: “Comincia con un vaso.”'],
      ['What does this viewer worry about, and how could the first 2 seconds calm it?', 'Di cosa si preoccupa questo spettatore, e come potrebbero calmarlo i primi 2 secondi?'],
      ['Which prop on the sheet shows the promise best, in action?', 'Quale oggetto della scheda mostra meglio la promessa, in azione?'],
      ['Which exact words on the last frame would make someone press follow?', 'Quali parole esatte nell’ultima inquadratura farebbero premere “segui”?']),
    h(['Hook (5 words): “Someone beats the record Friday.” Caption: “Retro Night, Friday 8 pm. 30 old games, pizza by the slice, free before 9. Top score wins a year of tokens.” Shots: A neon flickers on, with the hook as text (2s) → B joystick slam (3s) → E friends laughing (4s) → C cheese stretch (4s) → D new record (4s) = 17s. The words promise a challenge, the pictures show the fun.', 'Aggancio (5 parole): “Venerdì qualcuno batte il record.” Didascalia: “Serata Retro, venerdì ore 20. 30 giochi vintage, pizza al taglio, gratis prima delle 21. Chi fa il punteggio più alto vince un anno di gettoni.” Inquadrature: A il neon si accende, con l’aggancio come testo (2s) → B joystick sbattuto (3s) → E amici che ridono (4s) → C formaggio che fila (4s) → D nuovo record (4s) = 17s. Le parole promettono una sfida, le immagini mostrano il divertimento.'],
      ['What would make someone send this to a friend?', 'Cosa spingerebbe qualcuno a mandare questo video a un amico?'],
      ['What can the words say that no picture can show?', 'Cosa possono dire le parole che nessuna immagine può mostrare?'],
      ['Which shot should come last, so the invitation lands right after it?', 'Quale inquadratura deve venire per ultima, così che l’invito arrivi subito dopo?']),
  ],
  Selling: [
    h(['Marta, your coworking has coffee but nothing sweet. Our €12 box has 8 fresh pastries, delivered at 9. The café next door sells coffee; we bring what it doesn’t. Can I drop one off on Friday to try?', 'Marta, nel tuo coworking c’è il caffè ma niente di dolce. La nostra box da 12 € ha 8 pasticcini freschi, consegnata alle 9. Il bar accanto vende caffè; noi portiamo ciò che non ha. Posso lasciartene una venerdì da provare?'],
      ['What does Marta lack right now?', 'Cosa manca a Marta in questo momento?'],
      ['What would she answer to “we already have a café”?', 'Cosa risponderesti a “abbiamo già un bar”?'],
      ['What small question is easy to say yes to?', 'Quale piccola domanda è facile a cui dire di sì?']),
    h(['Subject: Your Lisbon rebrand. Dana, I loved how the Lisbon rebrand used just one colour. Quick yes/no question about how you price projects: ok if I send it? Just reply “yes”.', 'Oggetto: Il tuo rebrand di Lisbona. Dana, mi è piaciuto come il rebrand di Lisbona usa un solo colore. Una domanda sì/no su come prezzi i progetti: posso mandartela? Rispondi solo “sì”.'],
      ['What did all three ignored messages have in common?', 'Cosa avevano in comune i tre messaggi ignorati?'],
      ['What detail proves you looked at her work?', 'Quale dettaglio prova che hai guardato il suo lavoro?'],
      ['What is the tiniest thing you can ask?', 'Qual è la cosa più piccola che puoi chiedere?']),
    h(['1) “What would great sound feel like to you?” Then the price makes sense. 2) “What do yours not do on a loud train?” 3) “Totally fair. Can you test mine on tomorrow’s commute at 9?”', '1) “Che sensazione ti darebbe un suono ottimo?” Poi il prezzo ha senso. 2) “Cosa non fanno le tue su un treno rumoroso?” 3) “Giusto. Le provi sul tragitto di domani alle 9?”'],
      ['Which question makes them describe what they need?', 'Quale domanda li fa descrivere ciò che serve?'],
      ['What does their current pair fail at?', 'In cosa sbagliano le loro cuffie attuali?'],
      ['What time and place can you propose?', 'Che orario e luogo puoi proporre?']),
    h(['Hi Luca, thanks for trying a session on Tuesday. You said you hate crowds: we are quietest from 10 to 12, which suits night shifts. It’s €39 a month, cancel any time, and the first month is €29 until Sunday. Want me to save you a 10 am slot this week?', 'Ciao Luca, grazie per aver provato la lezione martedì. Mi hai detto che odi la folla: da noi è più tranquillo dalle 10 alle 12, comodo per chi lavora di notte. Costa 39 € al mese, disdici quando vuoi, e il primo mese è 29 € fino a domenica. Ti tengo un posto alle 10 questa settimana?'],
      ['How would this text feel if a friend had sent it?', 'Come sembrerebbe questo messaggio se lo avesse mandato un amico?'],
      ['Which sentences are pressure, and which are real facts about Luca?', 'Quali frasi sono pressione e quali sono fatti veri su Luca?'],
      ['Of the quiet hours, which one actually fits someone who works nights?', 'Tra le ore tranquille, quale va davvero bene a chi lavora di notte?']),
    h(['Headline: “Flat tyre? Fixed in 10 minutes.” Text: €5, and we tell you the price before we touch your bike. Every repair has a 3-month guarantee. Wednesdays 17:00–19:00, courtyard behind Block C. Just roll up.', 'Titolo: “Bici bucata? Riparata in 10 minuti.” Testo: 5 €, e ti diciamo il prezzo prima di toccare la bici. Ogni riparazione ha 3 mesi di garanzia. Mercoledì 17:00–19:00, cortile dietro il Blocco C. Basta presentarsi.'],
      ['What does a student with a flat tyre worry about?', 'Di cosa si preoccupa uno studente con una gomma a terra?'],
      ['Which facts calm that worry, and which only talk about the shop?', 'Quali fatti calmano quella preoccupazione, e quali parlano solo del negozio?'],
      ['What do they need to know to turn up on Wednesday?', 'Cosa devono sapere per presentarsi mercoledì?']),
    h(['Seller: “€240, and I check every colour. What matters most, price or Friday?” Buyer: “Friday matters most. The last printer got the colours wrong. Could you check them for free?” Seller: “Yes, a free colour check, and €205 if you promise next season’s menus.” Buyer: “Half now, half on delivery?” Seller: “Deal. 200 menus, €205, colour check, half now, rest on delivery, Friday.”', 'Venditore: “240 €, e controllo ogni colore. Cosa conta di più, prezzo o venerdì?” Compratore: “Conta il venerdì, e i colori: l’ultima tipografia li ha sbagliati. Me li controlli gratis?” Venditore: “Sì, prova colore gratis e 205 € se mi prometti i menu della prossima stagione.” Compratore: “Metà ora, metà alla consegna?” Venditore: “Affare fatto. 200 menu, 205 €, prova colore, metà ora, il resto alla consegna, venerdì.”'],
      ['Besides the price, what does each side really want?', 'Oltre al prezzo, cosa vuole davvero ciascuno dei due?'],
      ['What could you give that costs you little but matters to them?', 'Cosa puoi dare che ti costa poco ma conta per loro?'],
      ['Which single line would you both write down so the deal is clear?', 'Quale riga scrivereste entrambi perché l’accordo sia chiaro?']),
  ],
  Music: [
    h(['Instrument: soft piano, slow (60 bpm). Notes: C – E – G – C. It starts with one quiet C and ends on a held low C, like a deep breath.', 'Strumento: pianoforte morbido, lento (60 bpm). Note: DO – MI – SOL – DO. Parte con un DO piano e finisce su un DO grave tenuto, come un respiro profondo.'],
      ['Which instrument sounds warm and slow to you?', 'Quale strumento ti suona caldo e lento?'],
      ['How many notes fit in 6 seconds at a slow pace?', 'Quante note stanno in 6 secondi a ritmo lento?'],
      ['Which note feels like an ending?', 'Quale nota sembra una fine?']),
    h(['Song: “Let It Be”. Feeling: calm. Keep: the chorus melody. Change: slow it to 60 bpm and play it on one guitar. Add: soft rain. Drop: the drums. Result: a sleepy rainy-day version.', 'Canzone: “Let It Be”. Sensazione: calma. Tieni: la melodia del ritornello. Cambia: rallenta a 60 bpm e suona con una chitarra sola. Aggiungi: pioggia leggera. Togli: la batteria. Risultato: una versione assonnata da giorno di pioggia.'],
      ['What feeling should the remix give?', 'Che sensazione deve dare il remix?'],
      ['Which one part must stay so people recognise it?', 'Quale parte deve restare perché la riconoscano?'],
      ['What would you remove to make space?', 'Cosa toglieresti per fare spazio?']),
    h(['Melody over C–G: E E G G, then up to A. Words: “Go on, move, move!” Loudest beat on the first “move”.', 'Melodia su DO–SOL: MI MI SOL SOL, poi sale al LA. Parole: “Dai, muoviti, muoviti!” Battito più forte sul primo “muoviti”.'],
      ['What short pattern can repeat on C and G?', 'Quale breve schema può ripetersi su DO e SOL?'],
      ['Which word sells the shoe?', 'Quale parola vende la scarpa?'],
      ['Where is the strongest beat in the loop?', 'Dov’è il battito più forte nel giro?']),
    h(['1) Your coat still hangs behind the door. 2) I set two cups, then put one back. 3) Your song comes on, I stop mid-stride. 4) So I miss you. The light stays on. Lines 1 to 3 show a thing, a habit and a moment; only line 4 says the feeling, and all four tap out at 8 beats.', '1) Il tuo cappotto è ancora lì. 2) Metto due tazze, poi ne tolgo una. 3) Passa la tua canzone e mi fermo. 4) Mi manchi, e la luce resta accesa. Le righe da 1 a 3 mostrano un oggetto, un’abitudine e un momento; solo la riga 4 dice il sentimento, e tutte hanno circa la stessa lunghezza.'],
      ['What is the one thing all four lines are saying?', 'Qual è l’unica cosa che tutte e quattro le righe dicono?'],
      ['What would you see, hear or touch in a room where someone is missing?', 'Cosa vedresti, sentiresti o toccheresti in una stanza dove qualcuno manca?'],
      ['Which one line should say the feeling out loud, and does it tap out at the same length as the others?', 'Quale riga sola deve dire il sentimento a voce alta, e batte con la stessa lunghezza delle altre?']),
    h(['18:00 energy 2, slow, warm brushed drums. 19:00 energy 2, slow, soft keys, bass. 20:00 energy 3, medium, light handclap groove. 21:00 energy 5, fast, big singalong synth. 22:00 energy 3, medium, warm last-song glow. If the room goes quiet: go up one level at a time, never jump two.', '18:00 energia 2, lento, chitarra e spazzole. 19:00 energia 2, lento, tastiere morbide, basso. 20:00 energia 3, medio, groove con battimani. 21:00 energia 5, veloce, synth da cantare. 22:00 energia 3, medio, bagliore di chiusura. Se la sala si spegne: sali di un livello alla volta, mai di due.'],
      ['What should a guest feel when walking in at 18:00, and when leaving at 23:00?', 'Cosa deve sentire un ospite entrando alle 18:00, e uscendo alle 23:00?'],
      ['Where does the night peak, and what do you want people to feel right after it?', 'Dove ha il picco la serata, e cosa vuoi che la gente senta subito dopo?'],
      ['Which instrument or texture would you hear in the peak hour that you never hear in hour 1?', 'Quale strumento o texture senti nell’ora del picco e mai nella prima ora?']),
    h(['Clap: . . X . . . X . (stomp on steps 1 and 5). Call, steps 1 to 4: “Tide-walk, rea-dy?” Answer, steps 5 to 7: “Here we go!” The key word, go, lands on the clap at step 7.', 'Mani: . . X . . . X . (pestata sui passi 1 e 5). Richiamo, passi 1-4: “Ma-re, pron-ti?” Risposta, passi 5-8: “Tut-ti, vi-a!” Le sillabe forti, Tut e Vi, cadono sulla pestata e sul battito di mani.'],
      ['Which part should everyone be able to shout after hearing it once?', 'Quale parte devono poter gridare tutti dopo averla sentita una volta?'],
      ['On which steps does the rhythm rest, leaving a gap where words can breathe?', 'In quali passi il ritmo si ferma, lasciando uno spazio dove le parole respirano?'],
      ['Which single syllable of the answer is the strongest, and does it land on a hit?', 'Quale singola sillaba della risposta è la più forte, e cade su un colpo?']),
  ],
};
